"""Turn a compact parameter set into a full vehicle, and score it against requirements.

Layout, nose to tail:

    [nose cone] [nav bay] [canard module] [recovery bay] [booster + aft fins]

The nav bay is forward on purpose: GNSS antennas need sky view and want to be as far as
possible from the servo power wiring, and a fiberglass airframe is an RF shield, so the
antenna wants to sit under the (thin, non-conductive) nose shoulder region.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field, replace
from functools import lru_cache
from pathlib import Path

from . import aero, avionics, control, joints, mass as mass_mod, recovery, trajectory
from .geometry import BodyTube, FinSet, NoseCone, Rocket
from .motors import GENERIC, Motor, load_eng
from .packaging import SERVOS


@dataclass
class DesignParams:
    outer_diameter: float
    wall_thickness: float
    motor: Motor
    nose_fineness: float = 4.0
    nose_shape: str = "ogive"
    nav_bay_cal: float = 1.6  # bay lengths in calibers
    canard_module_cal: float = 1.8
    # 4.5 cal, and it is now CHECKED rather than assumed. It was a number someone typed,
    # and recovery.check_packing() exists because nothing had ever verified it. The first
    # run said it was 11 mm short -- but that verdict came from estimating packed volume as
    # budgeted mass / an assumed bulk density, and the budget carries a 280 g main against
    # a real Fruity Chutes Iris Ultra 60" Compact at 193 g. With the vendor's published
    # pack volumes standing in for the estimate, the hardware needs 4.33 cal and this bay
    # fits it with 13 mm to spare. The airframe was right; only the confidence in it was
    # missing. See design/recovery.py for the sourced numbers.
    recovery_bay_cal: float = 4.5
    booster_margin_cal: float = 1.2  # booster length beyond the motor
    # 1.30 cal, up from 0.85, and this is where the agility actually comes from.
    # Canard area buys Cm_delta directly and costs static margin, and at 1.30/1.70 the
    # vehicle trims at 1.90 cal nominal instead of 2.22 -- more lean per degree of throw,
    # which is worth far more than the canard's own normal force. See
    # scripts/agility_sweep.py stage 4 for what each tenth of a caliber costs in risk.
    # 1.30 -> 1.45 cal AT THE STRETCH FREEZE (Sep 2026, correction 62), and it is here
    # because correction 61's HINGE fix made it legal, not because anything aerodynamic
    # changed. 1.45 cal was scored and rejected twice before: the pre-freeze search had it
    # stopped at a 1.92x bearing margin against 2.0x, and the whole point of docs/12 section
    # 5 is that the hinge -- not stall, not static margin, not servo torque -- was the wall.
    # Correction 61 took the journal dia 6 -> dia 8 to make the 1.30 cal vehicle legal on a
    # horizontal launch, and that bought 2.27x at 1.45 cal as a side effect. The wall moved,
    # so the canard could.
    #
    # It is better than 1.30/1.70 on BOTH axes at once, which is rare enough to say plainly:
    # 8.97 -> 9.92 deg/s of peak heading rate AND P(SM < 1.0) 0.61% -> 0.45%. Growing the
    # aft set with it is what does that -- see aft_semispan_cal below. Turn radius
    # 990 -> 880 m.
    canard_semispan_cal: float = 1.45
    # Root chord and taper are set TOGETHER and hold panel area constant at 3188 mm^2.
    # 0.85/0.40 replaced 0.70/0.70 in Aug 2026: at the 35.4 deg sweep below, a more
    # sharply tapered panel recovers most of the authority the sweep costs (1.82 -> 1.93 g,
    # 394 -> 418 m of crossrange) because CNa rises as the tip unloads. It also reads more
    # like a real missile canard, which is why it was chosen -- the aerodynamics came out
    # ahead as well, which is rare enough to note.
    #
    # The cost is flutter: the root chord grows 55.6 -> 67.5 mm at a fixed 3.0 mm thickness,
    # so t/c falls 0.054 -> 0.044. This is now the parameter to watch if the panel ever
    # gets thinner. See docs/00-requirements.md section 8.
    #
    # THE FLUTTER MARGINS IN THIS PARAGRAPH'S HISTORY (5.42x -> 4.46x) WERE MEASURED AT THE
    # OLD 0.85 cal SEMISPAN and no longer describe this vehicle. At 1.30 cal the canard
    # aspect ratio is 2.18 and the margin is 3.50x -- still comfortably over 1.5x, and the
    # canards are not the flutter-critical set. The aft fins are, at 2.13x. Both are
    # regenerated by scripts/baseline.py; do not quote these numbers, run it.
    # 0.85 -> 1.1161 cal AND taper 0.40 -> 0.10 (correction 63). A COSMETIC change, asked
    # for as one and priced as one: the trapezoid read as a clipped panel with a wide tip
    # and the vehicle is meant to look like a canard missile. Root 67.5 -> 88.6 mm, tip
    # 27.0 -> 8.9 mm -- a 10:1 taper against 2.5:1 -- with the leading edge at 42.2 deg.
    #
    # THE RULE ABOVE STILL HOLDS, and it is why the root grew: root chord and taper are set
    # TOGETHER. Here they are set together with TWO constraints rather than one, because on
    # this airframe a canard outline is not free:
    #
    #   1. `canard_sweep_cal` below is solved so the HINGE STATION DOES NOT MOVE.
    #      `hinge.canard_hinge_station` is 0.20c of the MAC, so it depends on root, taper
    #      AND sweep -- change the outline naively and the shaft, the four bay collars, the
    #      four servos and the wall bores all move with it, which is a bay rebuild, not a
    #      cosmetic change. Solved, it lands within a nanometre of 521.720232 mm.
    #   2. Root chord is then set so SERVO TORQUE MARGIN IS NOT MADE WORSE. It is 2.067x
    #      and is one of the two tightest margins in the vehicle (docs/12 section 11), so a
    #      cosmetic change does not get to spend it. Hinge moment goes as panel area x mean
    #      chord, so this pins the area at +3.2%.
    #
    # WHAT IT COSTS: 9.92 -> 9.76 deg/s, -1.63%, against the 3% the change was budgeted.
    # WHAT IT BUYS, and none of this was the point: hinge bearing 2.11 -> 2.53x, root tang
    # 2.02 -> 2.46x, root skin 2.49 -> 2.99x, tang leading-edge clearance 17.96 -> 20.4 mm,
    # and P(SM < 1.0) 0.45% -> 0.36%. A sharper panel puts less area outboard, so the shaft
    # and the root joint both see less.
    #
    # WHAT IT ALSO COSTS, and it is the one margin that went the wrong way: CANARD FLUTTER
    # 4.50 -> 3.51x. `design/flutter.py` takes t/c on the ROOT chord, and the root chord is
    # what grew -- 0.0593 -> 0.0451. The paragraph above this one has warned about exactly
    # this since the 0.70/0.70 -> 0.85/0.40 change ("this is now the parameter to watch"),
    # and it was right to. 3.51x is still 2.3x the 1.5x requirement and the canards are not
    # the flutter-critical set -- the aft fins are, unchanged at 2.01x -- but a further
    # sharpening would spend this, not the structural margins above.
    canard_root_cal: float = 1.1161
    canard_taper: float = 0.10
    # Canard leading-edge sweep, calibers of axial offset from root LE to tip LE.
    # None means "match the aft fin sweep ANGLE", which is the design intent: the two sets
    # should read as one vehicle, and hardcoding a number here would silently drift the
    # moment `aft_sweep_cal` moved. Set a float to probe a different planform.
    #
    # This was 0.0 (a symmetric-taper trapezoid) until Aug 2026, not because anything chose
    # it but because the canards never had a sweep parameter while the aft fins did. That
    # default was the maximum-authority shape -- symmetric taper puts the mid-chord line at
    # zero sweep, which maximises CNa per unit area in aero.fin_cn_alpha -- so sweeping
    # costs authority. It is a deliberate trade, priced in docs/00-requirements.md section 5.
    #
    # Sweep does NOT change planform area, and it does NOT flip the hinge sign: both the
    # hinge (0.20c) and the panel CP (0.25c) are referenced to the same MAC, so the net
    # hinge moment stays restoring at any sweep. See correction 2 before assuming otherwise.
    # SET EXPLICITLY SINCE CORRECTION 63, and this is a deliberate break with the paragraph
    # above. `None` means "match the aft fin sweep ANGLE", whose stated reason is that the
    # two sets should read as one vehicle -- and at 30.7 deg against a 42.2 deg canard they
    # no longer do. That was the trade: the canard is meant to read as a missile canard,
    # which is a sharper delta than a stabilising fin, and the aft set is not.
    #
    # The number is NOT a styling choice. It is SOLVED, and it is the only free variable
    # left once the outline is chosen: it is what holds `hinge.canard_hinge_station` at
    # 521.720232 mm so that nothing on the hinge axis has to move. Re-solve it if root
    # chord or taper ever change again -- do not carry this value across.
    canard_sweep_cal: float | None = 1.316336
    # 1.70 cal, up from 1.55. Grown WITH the canards, not despite them: bigger canards
    # alone would take the margin below R1, and the aft set is what buys it back. The two
    # were searched jointly (they always must be -- see the frozen-baseline note below).
    # 1.70 -> 1.85 cal WITH THE CANARDS (correction 62). Same rule as the 1.30/1.70 freeze
    # and the reason it is restated: THESE TWO ARE SET JOINTLY OR NOT AT ALL. A 1.45 cal
    # canard alone takes the nominal static margin to 1.77 cal and P(SM < 1.0) to 1.9%,
    # straight through R1's 1% budget. The aft set is what buys it back -- 1.99 cal and
    # 0.45% -- and it costs almost nothing in turn rate because the canard's Cm_delta grew
    # at the same time.
    #
    # 2.00 cal was also legal and scored slightly better on risk (0.12%), and it was NOT
    # taken: it is more aft-fin area sitting in the canard wake for a turn rate that is
    # the same to two digits (9.93 vs 9.92 deg/s), and the interference model is the
    # weakest assumption in this project (docs/00 section 5). 1.85 is the smaller change.
    aft_semispan_cal: float = 1.85
    aft_root_cal: float = 1.90
    aft_taper: float = 0.45
    aft_sweep_cal: float = 1.10
    n_canards: int = 4
    n_aft_fins: int = 4
    fin_thickness: float = 0.0032
    # Key into packaging.SERVOS. Drives BOTH the actuator packaging check and the
    # servo line of the mass budget, so the two cannot disagree.
    servo: str = "kst_x08_plus"
    # Threaded rod + washer stack in the nose shoulder, metres from the nose tip.
    # REQUIRED, not optional: with none at all P(SM < 1.0) is 1.41% against R1's 1% limit.
    # 40 g is the minimum that satisfies R1 (0.97%, i.e. exactly on the edge); 60 g is the
    # design point at 0.79%.
    #
    # IT WAS 100 g, AND IT CAME DOWN BECAUSE IT STOPPED BEING WORTH MUCH. On the 0.85/1.55
    # airframe ballast was the cheapest margin available. At 1.30/1.70 the fins dominate
    # the CP so completely that the whole 0 -> 100 g sweep moves median SM only 1.83 ->
    # 1.96 cal -- a seventh of a caliber for 100 g carried at the very front of a 6.4 kg
    # vehicle. Spending 40 g of that on authority instead is simply a better trade, and it
    # is the one place in this freeze where a number went DOWN for a reason unrelated to
    # agility. Provision is still 300 g: this is the parameter you tune after weighing the
    # built vehicle, which is the whole argument in docs 7.1.
    nose_ballast_kg: float = 0.060
    nose_ballast_station: float = 0.191
    # 3.2 mm, and it is 3.2 because of how the panel is BUILT, not because of aerodynamics.
    #
    # The canard root has to take the shaft's tang -- a flat blade bonded into a slot in
    # the panel edge (docs/05, "The root joint"). Cutting that slot into a solid plate is a
    # deep, thin, blind cut needing a slitting saw on a mill. Building the panel as a
    # laminate avoids cutting it at all: the slot is simply a gap left in the middle sheet,
    # which is a flat shape anyone can cut before bonding. But then the panel's thickness
    # is the sum of three sheets, and it can only be a sum of thicknesses that are actually
    # SOLD. 0.6 / 2.0 / 0.6 is the best such stack; 0.6 / 1.8 / 0.6 was specified first and
    # 1.8 mm G10 is not stocked anywhere.
    #
    # So this moved 3.0 -> 3.2 for a manufacturing reason, and the reason is still good:
    # 0.6 / 2.0 / 0.6 is a stack you can buy. The margins quoted here when the change was
    # made (canard flutter 4.46x -> 4.92x, SM 2.03-2.52 -> 2.04-2.53 cal, crossrange
    # 424 -> 419 m) were all measured on the 0.85 cal / J449 vehicle and are HISTORY, not
    # current values -- the 1.30 cal panel is a different part on a different motor.
    # Current numbers come from scripts/baseline.py. See docs/00 section 8 and docs/05.
    #
    # The manufacturing argument is unaffected by the freeze; the panel got bigger, not
    # differently built. The laminate still needs a slot for the tang and the slot is still
    # a gap left in the middle sheet.
    #
    # 3.2 -> 3.6 mm AT THE 1.30 cal FREEZE, and this one is NOT optional. The bigger panel
    # puts 28.8 N through the root instead of 21.1 N, and its centre of pressure moved
    # outboard as well, so the bending at the wall went 0.610 -> 1.273 N.m -- it doubled.
    # At a 1.8 mm tang in a 3.2 mm panel that leaves 0.600 mm of skin spanning the slot,
    # working at 327 MPa against a 480 MPa flexural allowable: 1.47x, against the 2.0x this
    # project requires everywhere else. scripts/baseline.py fails it outright.
    #
    # 3.6 mm puts the skin at 0.800 mm and the margin at 2.65x. The laminate is still three
    # stocked sheets -- 0.8 / 2.0 / 0.8, and 0.8 mm is 1/32 inch, one of the most common G10
    # thicknesses there is -- so the manufacturing argument above survives intact. It costs
    # 1.93 -> 1.88 g of authority, about 2.6%, which is the cheapest fix on the list: a
    # thicker tang eats the skin it is trying to protect, and a wider one spans a wider
    # slot, so the panel is the only place to put the material.
    # 3.6 -> 4.0 mm AT THE HORIZONTAL FREEZE (Sep 2026, correction 61), and the reason is
    # the same one that took it 3.2 -> 3.6: the skin over the tang slot, which goes as
    # 1/t^2. A HORIZONTAL launch's maximum dynamic pressure is the burnout value at SEA
    # LEVEL rather than at 230 m of altitude -- 15.5 kPa against 12.4 -- and the deflection
    # cap moved 8.0 -> 9.2 deg on top of that, so the panel load went 27.1 -> 38.0 N and the
    # 0.800 mm skin fell to 1.93x against this project's 2.0x.
    #
    # 4.0 mm puts the skins at 1.000 mm and the margin at 3.09x. The laminate is still three
    # STOCKED sheets and the middle one is still the 2.0 mm slot: 1.0 / 2.0 / 1.0, and 1.0 mm
    # G10 is as common as 0.8. The manufacturing argument above survives untouched.
    #
    # It costs 1.4% of the horizontal turn rate and 1.9% of the vertical one (6.47 -> 6.35
    # deg/s) -- four heavier panels are a heavier vehicle -- and that feedback is REAL and
    # was nearly missed: `scripts/horizontal_agility_sweep.py` sized this laminate and then
    # reported the flight it had flown at the OLD one, which is docs/11's "upper bound until
    # the structural chain has been run" for the third time. It converges in one pass.
    #
    # The TANG does not improve with a thicker laminate (2.53x here) because it carries the
    # panel force, not the skin's bending. A second stocked step would buy nothing.
    canard_thickness: float = 0.0040
    material_density: float = 1850.0

    @property
    def label(self) -> str:
        return f"D{self.outer_diameter * 1000:.0f}/{self.motor.name}"


# ----------------------------------------------------------------------------------------
# THE FROZEN BASELINE -- single source of truth
# ----------------------------------------------------------------------------------------
# Every script builds its vehicle from baseline() below. Do not copy these numbers into a
# script; import them. Six scripts each used to carry their own copy, they drifted apart
# from the documentation, and reconciling that cost a full day.
#
# Fin semispans are the dataclass defaults above (canard 1.30 cal, aft 1.70 cal), set
# jointly -- see docs/00-requirements.md section 7. Sizing the two sets independently was
# the original mistake: canard area buys control authority but costs static margin, aft
# area buys margin but costs authority.
#
# THEY WERE 0.85 / 1.55 UNTIL THIS FREEZE, chosen by scripts/robustness.py's constrained
# search, which maximised CROSSRANGE. scripts/agility_sweep.py re-ran the same style of
# search against TURN RATE instead, with three constraints robustness.py never had (the
# +/-16 g accelerometer, motor case length against the built mount tube, and the flutter
# fix priced as G10 stock sizes) -- and it moved the motor as well as the fins, because
# those three couple. The new point is the last row that passes every requirement; see
# docs/11 section 7 for the ladder showing what each requirement costs.
#
# WHAT THIS FREEZE IS NOT: it is not a step toward a lower margin. Stage 4 of the sweep
# shows the next rung down (1.30/1.55, 25 g ballast) buys 10% more turn rate for a 6x
# increase in P(SM < 1.0), straight through R1's budget. 1.90 cal is where the risk curve
# turns, not a waypoint.

ROOT = Path(__file__).resolve().parents[1]

BASELINE_OD = 0.0794  # 3.0 in fiberglass, 79.4 mm OD
BASELINE_WALL = 0.0023

# THE MOTOR IS CHOSEN FOR AGILITY, AND THAT MEANS A SMALLER ONE. This is the least
# intuitive number in the file, so it gets the long comment.
#
# scripts/motor_trade.py picked the Cesaroni J449 by maximising CROSSRANGE -- how far
# sideways the vehicle gets -- and on that metric a bigger motor always wins, because
# crossrange rewards both authority and time of flight. `scripts/agility_sweep.py` asks a
# different question, the one that matches what this vehicle is for: how fast does the
# VELOCITY VECTOR turn. Heading rate is
#
#     omega = n * g0 / V
#
# so speed appears in the numerator of n (through q ~ V^2) and again in the denominator.
# Doubling speed quadruples the g and only doubles the turn rate -- and turn RADIUS,
# V^2/(n g0), does not improve at all, because the two V^2 terms cancel exactly.
#
# Meanwhile every requirement that actually binds is triggered by speed: the +/-16 g
# accelerometer (design/estimation.ACCEL_16G -- the K2050ST peaks at 31.4 g axial and
# blinds the estimator), R5's Mach cap, R6's apogee cap, fin flutter, and servo hinge
# moment. None of them is triggered by static margin except R1 itself.
#
# So the search spends its budget on a SLOWER motor that leaves all of those slack, and
# buys the turn back through lean. The AeroTech J401FJ, 1105 N*s against the J449's 1260:
# 6.91 deg/s and a 1.13 km turn radius, against 4.40 deg/s and 2.04 km on the J449.
# 1.6x the turn rate on 12% less impulse.
#
# It also fits the mount tube that docs/09 already built: 325 mm case against 332.08 mm
# of tube. Most K motors do not, which is a build constraint the model cannot see because
# `build_vehicle` grows the booster parametrically.
#
# The J449 selection is kept in docs/02 as history -- it was the right answer to the
# question motor_trade.py was asking.
BASELINE_MOTOR_FILE = ROOT / "data" / "motors" / "AeroTech_J401FJ.eng"


@lru_cache(maxsize=1)
def baseline_motor() -> Motor:
    """The frozen motor, falling back to a placeholder if the catalogue is not downloaded."""
    if BASELINE_MOTOR_FILE.exists():
        return load_eng(BASELINE_MOTOR_FILE)
    return GENERIC["J-54"]


def baseline(motor: Motor | None = None, **overrides) -> DesignParams:
    """The frozen baseline vehicle.

    Pass a motor to swap it (motor trade studies); pass keyword overrides to probe a
    variation without disturbing the frozen values.
    """
    params = DesignParams(
        outer_diameter=BASELINE_OD,
        wall_thickness=BASELINE_WALL,
        motor=motor if motor is not None else baseline_motor(),
    )
    return replace(params, **overrides) if overrides else params


def build_vehicle(p: DesignParams) -> Rocket:
    d = p.outer_diameter
    nose = NoseCone(
        length=p.nose_fineness * d,
        base_diameter=d,
        shape=p.nose_shape,  # type: ignore[arg-type]
        wall_thickness=p.wall_thickness,
        material_density=p.material_density,
    )

    booster_len = p.motor.length + p.booster_margin_cal * d
    tubes = [
        BodyTube(p.nav_bay_cal * d, d, p.wall_thickness, p.material_density, "nav bay"),
        BodyTube(p.canard_module_cal * d, d, p.wall_thickness, p.material_density, "canard module"),
        BodyTube(p.recovery_bay_cal * d, d, p.wall_thickness, p.material_density, "recovery bay"),
        BodyTube(booster_len, d, p.wall_thickness, p.material_density, "booster"),
    ]

    x_canard_module = nose.length + tubes[0].length
    canard_root = p.canard_root_cal * d

    # Sweep angle is what the eye reads, so match the ANGLE rather than the caliber offset --
    # the two sets have different semispans, so equal offsets would not look equal.
    if p.canard_sweep_cal is None:
        aft_sweep_angle = math.atan2(p.aft_sweep_cal, p.aft_semispan_cal)
        canard_sweep = p.canard_semispan_cal * math.tan(aft_sweep_angle) * d
    else:
        canard_sweep = p.canard_sweep_cal * d
    canards = FinSet(
        count=p.n_canards,
        root_chord=canard_root,
        tip_chord=canard_root * p.canard_taper,
        semispan=p.canard_semispan_cal * d,
        sweep_length=canard_sweep,
        x_root_le=x_canard_module + 0.5 * (tubes[1].length - canard_root),
        thickness=p.canard_thickness,
        body_diameter=d,
        material_density=p.material_density,
        name="canards",
    )

    total_length = nose.length + sum(t.length for t in tubes)
    aft_root = p.aft_root_cal * d
    aft_fins = FinSet(
        count=p.n_aft_fins,
        root_chord=aft_root,
        tip_chord=aft_root * p.aft_taper,
        semispan=p.aft_semispan_cal * d,
        sweep_length=p.aft_sweep_cal * d,
        x_root_le=total_length - aft_root,
        thickness=p.fin_thickness,
        body_diameter=d,
        material_density=p.material_density,
        name="aft fins",
    )

    return Rocket(nose=nose, tubes=tubes, aft_fins=aft_fins, canards=canards)


@dataclass
class Evaluation:
    params: DesignParams
    rocket: Rocket
    masses: mass_mod.MassResult
    flight: trajectory.Flight
    pitch: control.AuthorityResult | None
    roll_aligned: control.RollResult | None
    roll_interdig: control.RollResult | None
    crossrange: float
    control_seconds: float
    sm_without_canards: float
    packing: recovery.PackingResult
    violations: list[str]
    warnings: list[str] = field(default_factory=list)
    # The deflection every derivative above was evaluated at. Recorded because it was NOT,
    # and D8 found three callers using three different values while quoting each other's
    # answers -- see DEFLECTION_LIMIT_DEG. An Evaluation that does not carry its own
    # deflection cannot be checked against the one a document claims it used.
    deflection_deg: float = 0.0

    @property
    def feasible(self) -> bool:
        return not self.violations


# Axial room left between the nose ballast washer stack and the first board behind it on
# the same threaded rod. 20 mm is a nut, a washer and somewhere to get a spanner.
NOSE_BALLAST_CLEARANCE = 0.020  # m

# The recovery bay's internal bulkhead, as BUILT rather than as allowed for: a 4.8 mm G-10
# disc with a 3 mm epoxy fillet on each face. `recovery.BULKHEAD_THICKNESS` is still 12.0 mm
# and is still the right thing for a bulkhead nobody has designed; this one has been
# designed, so it is measured. Kept here rather than imported from seal.py because seal.py
# imports recovery.py and the cycle is not worth the tidiness.
INTERNAL_BULKHEAD_STACK = 0.0108  # m

# THE TWO DEFLECTION LIMITS, and they are different numbers for a physical reason.
#
# These lived in `scripts/baseline.py` until D8 went looking for the roll rate and found
# THREE deflections in use across the project: `baseline.py` evaluated at 8 deg,
# `avionics_trade.py` took `evaluate`'s 6 deg default, and docs/06 quoted the 6 deg answer
# under an 8 deg label. Steady roll rate is LINEAR in deflection, so that is not a
# rounding difference -- it is 594, 1783 and 2377 deg/s, and the gyro requirement was
# written against the middle one. Correction 4 all over again: a constant that lives in
# a script drifts from the document that quotes it. They live here now.
#
# The limit is a PITCH/YAW limit. Pitch needs the authority: it is fighting a stable vehicle
# with 2.1-2.6 cal of margin. Roll is not -- roll inertia is tiny, the canards are ganged,
# and full deflection spins the vehicle far faster than any control law wants. The cap is
# what keeps the rate gyro inside its range (design/estimation.py), so it is a SENSING
# requirement as much as a control one, and lifting it saturates the gyro.
# 8.0 -> 9.2 deg AT THE HORIZONTAL FREEZE (Sep 2026, correction 61), AND THE PARAGRAPH
# ABOVE WAS WRONG ABOUT WHY 8.0 WAS THERE. It says the cap "is what keeps the rate gyro
# inside its range, so it is a SENSING requirement" -- but read `estimation.check_estimation`
# and that argument is entirely about the ROLL axis: it compares gyro full scale against the
# roll rates at ROLL_COMMAND_CAP_DEG and at DEFLECTION_LIMIT_DEG. A pitch/yaw deflection on
# a stable vehicle produces no large body rate; it trims to a slightly larger alpha.
#
# Checked rather than argued: `check_estimation` and `mag_aided_roll_error` return IDENTICAL
# numbers at 8.0 and at 9.19 deg -- 647.96 deg/s of roll rate, 0.079 deg of aided roll error,
# ok=True -- because the roll rate they budget against is a function of ROLL_COMMAND_CAP_DEG
# and this constant does not appear in it. THE ROLL CAP IS THE SENSING LIMIT. This one is not.
#
# What actually caps pitch/yaw is canard STALL, and it is a cliff rather than a rolloff:
# local alpha is alpha_trim + delta, 12 deg is `control.STALL_LIMIT_DEG`, and past it
# `pitch_authority` applies a post-stall haircut to a vehicle that is also trimming further.
# On the frozen vehicle 10.0 deg of deflection makes 9.76 deg/s and 10.5 deg makes 6.15 --
# BELOW the 7.81 that 8.0 deg was already making. 9.2 deg is 10.95 deg of local alpha, which
# leaves 1.05 deg of headroom against a stall limit that is itself a modelling constant
# (linear, attached, small-alpha). One degree is one gust, and it is the minimum this
# project should fly. Do not raise this without measuring the stall angle.
#
# Worth 7.95 -> 8.97 deg/s of peak heading rate on a horizontal launch. See
# docs/12-horizontal-agility.md sections 5.4 and 8 (R13).
DEFLECTION_LIMIT_DEG = 9.2

# UNCHANGED, and it must stay unchanged for the line above to be true. Correction 58 settled
# that uncapping roll breaks the thing L1 exists to do; correction 61 relies on that having
# stayed settled, because it is what keeps the gyro out of the pitch/yaw argument.
ROLL_COMMAND_CAP_DEG = 2.0

LIMITS = dict(
    sm_min=1.4,  # minimum over the flight, which occurs at rail exit (motor loaded)
    sm_max=3.0,  # above this the vehicle weathercocks hard and fights the controller
    rail_exit_min=15.0,
    twr_min=5.0,
    mach_max=0.80,
    apogee_min_m=450.0,
    # The field has no altitude waiver ceiling, so this cap is no longer regulatory. It is
    # set by recovery footprint instead: see scripts/recovery_study.py. At 1600 m the walk
    # to the landing point is about 1 km in a 15 mph wind, which is recoverable on foot
    # within a launch window. Past that, recovery risk per flight starts to dominate, and
    # this project needs five or six flights with the data intact.
    apogee_max_m=1600.0,
    lateral_g_min=0.5,
)


def evaluate(
    p: DesignParams,
    deflection_deg: float = 6.0,
    rail_length: float = 3.66,
    rail_angle_deg: float = 5.0,
) -> Evaluation:
    rocket = build_vehicle(p)
    # Where the nose-mounted avionics actually sit is geometry, not a guess: the cone
    # narrows going forward, so `check_nose_packing` finds the most forward station at which
    # the two boards still fit on a sled behind the ballast, and their centroid follows from
    # that. Hardcoding a station here would drift the moment the nose fineness changed.
    nose_fit = avionics.check_nose_packing(
        rocket.nose, forward_limit=p.nose_ballast_station + NOSE_BALLAST_CLEARANCE)
    masses = mass_mod.build_mass(
        rocket, p.motor,
        servo_mass_each=SERVOS[p.servo].mass, n_servos=p.n_canards,
        nose_ballast_kg=p.nose_ballast_kg, nose_ballast_station=p.nose_ballast_station,
        nose_avionics_station=nose_fit.centroid,
    )
    flight = trajectory.simulate(
        rocket, p.motor, masses, rail_length=rail_length, rail_angle_deg=rail_angle_deg
    )

    violations: list[str] = []
    if flight.thrust_to_weight < LIMITS["twr_min"]:
        violations.append(f"T/W {flight.thrust_to_weight:.1f} < {LIMITS['twr_min']}")
    if flight.rail_exit_velocity < LIMITS["rail_exit_min"]:
        violations.append(f"rail exit {flight.rail_exit_velocity:.0f} m/s low")
    if flight.max_mach > LIMITS["mach_max"]:
        violations.append(f"Mach {flight.max_mach:.2f} > {LIMITS['mach_max']}")
    if flight.min_static_margin < LIMITS["sm_min"]:
        violations.append(f"SM {flight.min_static_margin:.2f} < {LIMITS['sm_min']} cal")
    if flight.max_static_margin > LIMITS["sm_max"]:
        violations.append(f"SM {flight.max_static_margin:.2f} > {LIMITS['sm_max']} cal")
    if not (LIMITS["apogee_min_m"] <= flight.apogee <= LIMITS["apogee_max_m"]):
        violations.append(f"apogee {flight.apogee:.0f} m outside window")

    # Will the recovery hardware physically go in the tube? `recovery_bay_cal` was an
    # assumed constant for a long time and nothing checked it. A canopy that does not fit
    # is not a soft failure: it is a rocket that cannot be assembled on the pad, found on
    # launch day.
    # THE BAY LENGTH HANDED TO THIS CHECK IS NOT THE TUBE LENGTH. `design/joints.py` settles
    # what the couplers cost: a coupler is a tube and its bore is still usable, so it is not
    # a length penalty -- but the bore over that span is 70.2 mm rather than 74.8, and for
    # something that PACKS that is a volume penalty. `equivalent_length` restates the bay as
    # the full-bore cylinder of the same volume, which is the only honest way to hand a bore
    # profile to a length-based check.
    bays = joints.budgets(rocket, p.wall_thickness)
    rec_tube = next(t for t in rocket.tubes if t.name == "recovery bay")

    # THE HARNESS IS SIZED, NOT BUDGETED. Its volume used to be the mass budget's
    # `shock_cord_and_links` divided by an assumed bulk density -- an unchecked number turned
    # into a volume by a guess, and a quarter of the bay. `recovery.size_harness` picks the
    # webbing from the load it actually carries, with a knot derating, and the answer was
    # two sizes down from 1 inch tubular nylon.
    #
    # The load comes from `seal.opening_shock` at its infinite-mass bound, which is the same
    # number the aft gas seal's U-bolt is checked against. One load, two parts, no chance of
    # them disagreeing.
    from . import atmosphere, seal as seal_mod
    _main = recovery.Canopy(
        "main", recovery.size_for_descent_rate(masses.dry_mass, 5.0), 2.2)
    _drogue = recovery.Canopy("drogue", 0.457, 1.5)
    opening_load = seal_mod.opening_shock(
        masses.dry_mass, _drogue.descent_rate(masses.dry_mass, 200.0),
        _main.cd_a, atmosphere.density(200.0), 1.7)
    harness = recovery.size_harness(rocket.length, opening_load)

    # And the internal bulkhead is a MEASURED stack now, not a 12 mm allowance: a 4.8 mm
    # G-10 disc with a 3 mm fillet on each face (design/seal.py). Carrying the allowance
    # after the part exists is the same error as the mass budget's 240 g placeholder against
    # 63 g of measured hardware (correction 20).
    internal = seal_mod.internal_bulkhead_from_evaluation
    packing = recovery.check_packing(
        rec_tube.inner_diameter, bays["recovery bay"].equivalent_length,
        compartments=recovery.default_soft_goods(
            inner_diameter=rec_tube.inner_diameter, harness=harness),
        bulkhead_thickness=INTERNAL_BULKHEAD_STACK)
    if not packing.fits:
        violations.append(
            f"recovery bay {rec_tube.length * 1000:.0f} mm, needs "
            f"{packing.required_length * 1000:.0f} mm for the chutes "
            f"({packing.required_length / p.outer_diameter:.2f} cal)"
        )

    # WARNINGS, not violations, and the distinction is deliberate.
    #
    # A violation says the vehicle as specified cannot fly. A warning says something is
    # wrong with the vehicle as ESTIMATED, and the two are not the same claim. The nav bay
    # check below is built entirely from component envelopes for parts nobody has chosen
    # yet -- D7 and D8 are open -- and correction 5 is what happens when an estimate-driven
    # shortfall is treated as a fact: the recovery bay was declared 11 mm short, the frozen
    # airframe was lengthened, and the shortfall was not in the hardware.
    #
    # So it does not flip `feasible`. It also does not get to be silent, because a check
    # that cannot fail is not evidence of anything.
    warnings: list[str] = []

    # The harness has to be strong enough, and the mass budget has to agree with the part
    # that was sized. Two checks because there are two ways for this to go wrong and only
    # one of them is about strength.
    if not harness.ok:
        violations.append(
            f"harness {harness.webbing.name} runs {harness.margin:.1f}x against the "
            f"{opening_load:.0f} N opening shock after knots, short of "
            f"{recovery.HARNESS_MARGIN_REQUIRED:.1f}x")
    budgeted = (recovery.DEFAULT_BUDGET_HARNESS if hasattr(recovery, "DEFAULT_BUDGET_HARNESS")
                else mass_mod.DEFAULT_RECOVERY_BUDGET["shock_cord_and_links"])
    if abs(budgeted - harness.mass) > 0.005:
        warnings.append(
            f"mass.py budgets {budgeted * 1000:.0f} g for the harness and "
            f"recovery.size_harness() makes it {harness.mass * 1000:.0f} g -- the packing "
            f"check and the mass budget are describing different parts")

    # Is the measured CAD inertia still a measurement of THIS vehicle? A warning, by the
    # rule two paragraphs up: the airframe flies, the ESTIMATE is what is wrong. But it is
    # the loudest kind of estimate error -- roll inertia sets the bandwidth every control
    # gain is scheduled against, and a stale tensor looks exactly like a fresh one.
    warnings.extend(control.check_measured_geometry(rocket))

    nav = bays["nav bay"]
    # Check the packing against the width of the sled that EXISTS, not against
    # avionics.SLED_WIDTH_FRACTION's fallback guess. Imported here rather than at module
    # scope because design/sled.py imports avionics, and avionics must not import back.
    from . import sled as sled_mod
    nav_sled_width = sled_mod.max_plate_width(
        nav.min_bore,
        max(sled_mod.stack_height(c) for c in avionics.NAV_BAY_STACK + [sled_mod.LOOM]))
    nav_pack = avionics.check_packing(
        nav.min_bore, nav.usable_length, avionics.NAV_BAY_STACK, end_closures=0,
        width_fraction=nav_sled_width / nav.min_bore)
    if not nav_pack.fits:
        was = avionics.check_packing(
            nav.min_bore, nav.usable_length, avionics.DEFAULT_STACK, end_closures=0)
        warnings.append(
            f"nav bay {nav.usable_length * 1000:.0f} mm usable needs "
            f"{nav_pack.required_length * 1000:.0f} mm of sled on estimated envelopes, "
            f"short by {-nav_pack.margin * 1000:.0f} mm (was "
            f"{was.required_length * 1000:.0f} mm before the tracker and radio went to the "
            f"nose); {len(nav_pack.estimated)} of {len(nav_pack.components)} parts are "
            f"guesses until D7 closes. See scripts/avionics_report.py and "
            f"scripts/sled_report.py"
        )
    if not nose_fit.fits:
        warnings.append(
            f"the nose cannot hold the relocated stack: {nose_fit.reason}")

    # D7 closed with parts lighter than the budget guessed: the custom board integrates the
    # GNSS and IMU that had their own lines, and a real StratoLoggerCF is 10.8 g against a
    # budgeted 60. NOT applied, for correction 20's reason -- it is a vehicle-level change,
    # 114 g at station 0.381 m is forward of the CG so removing it costs static margin, and
    # the board's own 45 g is a LAYOUT TARGET rather than a built part.
    #
    # This used to say "settle it with D8". D8 IS NOW CLOSED AND IT DID NOT SETTLE IT, which
    # is worth being explicit about rather than quietly moving the pointer: D8 added a
    # magnetometer to a board whose mass was already a target, so the number it would change
    # is a guess either way. Nothing settles this but a scale. It belongs to docs/01 step 5,
    # "weigh every component and replace the budget in design/mass.py with measurements" --
    # and until then flagging beats applying, which is the whole point of it being a warning.
    bay_budget_kg = sum(v for k, v in mass_mod.DEFAULT_AVIONICS_BUDGET.items()
                        if k not in mass_mod.NOSE_AVIONICS)
    selected_kg = sum(c.mass for c in avionics.NAV_BAY_STACK) + 0.080 + 0.150
    if abs(bay_budget_kg - selected_kg) > 0.020:
        warnings.append(
            f"nav bay budget {bay_budget_kg * 1000:.0f} g against {selected_kg * 1000:.0f} g "
            f"of D7-selected parts (+80 g wiring, +150 g sled) -- the budget is "
            f"{(bay_budget_kg - selected_kg) * 1000:.0f} g heavy since D7 closed. Not "
            f"applied: it is forward of the CG, so it costs static margin, and the board's "
            f"mass is a layout target. D8 did NOT settle this -- nothing but a scale will. "
            f"docs/01 step 5")

    # Control assessment at the highest-q point after burnout, where authority is best.
    coast = [pt for pt in flight.points if pt.t >= flight.burnout_time]
    pitch = roll_a = roll_i = None
    sm_bare = float("nan")
    if coast:
        pt = max(coast, key=lambda q: q.q)
        pitch = control.pitch_authority(rocket, pt, pt.mass, deflection_deg)
        roll_a = control.roll_authority(
            rocket, pt, pt.mass, deflection_deg, control.InterferenceModel.aligned()
        )
        roll_i = control.roll_authority(
            rocket, pt, pt.mass, deflection_deg, control.InterferenceModel.interdigitated()
        )
        # Static margin is a derivative, so it does not change with deflection. What the
        # canards do is add a forward normal-force contribution that reduces the margin
        # relative to the same airframe without them. Quantify that penalty explicitly:
        # it is the cost you pay for control authority.
        bare = replace(rocket, canards=None)
        sm_bare = aero.stability(bare, pt.cg, pt.mach).static_margin_cal
        if pitch.lateral_accel_g < LIMITS["lateral_g_min"]:
            violations.append(f"lateral {pitch.lateral_accel_g:.2f} g < {LIMITS['lateral_g_min']}")
        if pitch.stalled:
            violations.append(f"canard stall at {deflection_deg:.0f} deg")

    crossrange, seconds = control.achievable_crossrange(rocket, flight, masses, deflection_deg)

    return Evaluation(
        params=p,
        rocket=rocket,
        masses=masses,
        flight=flight,
        pitch=pitch,
        roll_aligned=roll_a,
        roll_interdig=roll_i,
        crossrange=crossrange,
        control_seconds=seconds,
        sm_without_canards=sm_bare,
        packing=packing,
        violations=violations,
        warnings=warnings,
        deflection_deg=deflection_deg,
    )
