"""Run one SU2 case on a mesh built by cfd/mesh.py and reduce it to the numbers the design uses.

    .venv-cfd/bin/python cfd/run.py --case roll5 --level medium [--np 8] [--iter 2500]

Solver: SU2 v8.5.0, compressible EULER (inviscid), Mach 0.45, sea level -- the horizontal
flight's max-q condition (R15's primary mode; docs/12). Euler is the right fidelity for
the questions asked of it: lift slopes, centre-of-pressure locations, hinge moments and
induced roll are pressure-dominated and Reynolds-insensitive while the flow is attached.
It CANNOT answer the stall question (separation is a viscous phenomenon) -- that limit is
stated wherever a result depends on it.

HOW THE HINGE MOMENTS ARE GOT, and why it is exact. SU2 reports each marker's total force F
and moment M_O about the reference origin (the nose tip). The moment of that same load
about any other line through point P along unit axis a is

    M_hinge = (M_O - P x F) . a

which needs no re-integration of the surface pressure. Each canard's hinge axis passes
through (hinge_x, 0, 0) along the panel's own clocked span direction (0, cos phi, sin phi)
-- a deflection rotates the panel about that axis, and it does not move it.

Installing SU2 (free, LGPL): see cfd/README.md. The binary is found via $SU2_RUN or
~/opt/su2native/bin, and mpirun via $MPIRUN or the `su2build` conda env.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "out" / "cfd"
MACH = 0.45
P_INF = 101325.0
T_INF = 288.15
GAMMA = 1.4

MARKERS = ["BODY"] + [f"CANARD{i}" for i in range(4)] + [f"FIN{i}" for i in range(4)]


def su2_bin() -> Path:
    for base in (os.environ.get("SU2_RUN"), str(Path.home() / "opt" / "su2native" / "bin")):
        if base and (Path(base) / "SU2_CFD").exists():
            return Path(base) / "SU2_CFD"
    raise SystemExit("SU2_CFD not found -- see cfd/README.md")


def mpirun() -> str:
    cand = [os.environ.get("MPIRUN"),
            str(Path.home() / "miniconda3" / "envs" / "su2build" / "bin" / "mpirun"),
            shutil.which("mpirun")]
    for c in cand:
        if c and Path(c).exists():
            return c
    raise SystemExit("mpirun not found -- see cfd/README.md")


def write_config(case_dir: Path, meta: dict, iters: int) -> Path:
    g = meta["geometry"]
    d = g["d"]
    a_ref = math.pi * d**2 / 4
    cfg = f"""% generated by cfd/run.py -- do not edit, regenerate
SOLVER= EULER
MATH_PROBLEM= DIRECT
RESTART_SOL= NO
MACH_NUMBER= {MACH}
AOA= {meta['alpha']}
SIDESLIP_ANGLE= 0.0
FREESTREAM_PRESSURE= {P_INF}
FREESTREAM_TEMPERATURE= {T_INF}
REF_ORIGIN_MOMENT_X= 0.0
REF_ORIGIN_MOMENT_Y= 0.0
REF_ORIGIN_MOMENT_Z= 0.0
REF_LENGTH= {d}
REF_AREA= {a_ref}
MARKER_EULER= ( {', '.join(MARKERS)}, STING )
MARKER_FAR= ( FARFIELD )
MARKER_PLOTTING= ( {', '.join(MARKERS)} )
MARKER_MONITORING= ( {', '.join(MARKERS)} )
NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES
CFL_NUMBER= 2.0
CFL_ADAPT= YES
CFL_ADAPT_PARAM= ( 0.7, 1.1, 1.0, 25.0 )
% Agglomeration multigrid: on a 1.9M-cell tet mesh the single-grid solver stalls its
% residual around 1e-2 and the forces are still drifting 15% at 400 iterations. 3 levels
% is what moves the low-frequency error (the base/sting region) out.
MGLEVEL= 3
MGCYCLE= W_CYCLE
MG_PRE_SMOOTH= ( 1, 2, 3, 3 )
MG_POST_SMOOTH= ( 0, 0, 0, 0 )
MG_CORRECTION_SMOOTH= ( 0, 0, 0, 0 )
MG_DAMP_RESTRICTION= 0.75
MG_DAMP_PROLONGATION= 0.75
CONV_NUM_METHOD_FLOW= ROE
MUSCL_FLOW= YES
SLOPE_LIMITER_FLOW= VENKATAKRISHNAN_WANG
VENKAT_LIMITER_COEFF= 0.05
TIME_DISCRE_FLOW= EULER_IMPLICIT
LINEAR_SOLVER= FGMRES
LINEAR_SOLVER_PREC= ILU
LINEAR_SOLVER_ERROR= 1E-4
LINEAR_SOLVER_ITER= 10
ITER= {iters}
CONV_FIELD= RMS_DENSITY
CONV_RESIDUAL_MINVAL= -9.5
CONV_STARTITER= 10
MESH_FILENAME= mesh.su2
MESH_FORMAT= SU2
SCREEN_OUTPUT= ( INNER_ITER, RMS_DENSITY, LIFT, DRAG, MOMENT_Y )
HISTORY_OUTPUT= ( ITER, RMS_RES, AERO_COEFF, AERO_COEFF_SURF )
OUTPUT_FILES= ( RESTART, SURFACE_PARAVIEW, PARAVIEW )
OUTPUT_WRT_FREQ= 500
SCREEN_WRT_FREQ_INNER= 25
HISTORY_WRT_FREQ_INNER= 5
"""
    path = case_dir / "config.cfg"
    path.write_text(cfg)
    return path


def run(case_dir: Path, nproc: int, iters: int) -> None:
    meta = json.loads((case_dir / "meta.json").read_text())
    cfg = write_config(case_dir, meta, iters)
    cmd = [mpirun(), "-np", str(nproc), str(su2_bin()), cfg.name]
    with open(case_dir / "su2.log", "w") as log:
        subprocess.run(cmd, cwd=case_dir, stdout=log, stderr=subprocess.STDOUT, check=True)


def _last_row(case_dir: Path) -> dict:
    with open(case_dir / "history.csv") as fh:
        rows = list(csv.reader(fh))
    head = [h.strip().strip('"').strip() for h in rows[0]]
    return {h: float(v) for h, v in zip(head, rows[-1])}, [
        {h: float(v) for h, v in zip(head, r)} for r in rows[1:]]


def reduce(case_dir: Path) -> dict:
    """Per-marker force/moment coefficients and derived quantities for one case."""
    meta = json.loads((case_dir / "meta.json").read_text())
    last, hist = _last_row(case_dir)
    g = meta["geometry"]
    d = g["d"]
    res: dict = dict(case=meta["case"], level=meta["level"], alpha=meta["alpha"],
                     defl=meta["defl"], n_cells=meta["n_cells"], iters=len(hist))

    def coeff(marker, name):
        # SU2 8.5 writes per-marker columns as "CFx(BODY)"; the @ form is older.
        for key in (f"{name}({marker})", f"{name}@{marker}", f"{name}_{marker}"):
            if key in last:
                return last[key]
        raise KeyError(f"{name}({marker}) not in history.csv; have "
                       f"{[k for k in last if marker in k][:6]}")

    comp = {}
    for m in MARKERS:
        F = [coeff(m, "CFx"), coeff(m, "CFy"), coeff(m, "CFz")]
        M = [coeff(m, "CMx"), coeff(m, "CMy"), coeff(m, "CMz")]
        comp[m] = dict(F=F, M=M)
    res["components"] = comp

    # hinge moments, coefficient form (moment / (q A d))
    hx = g["hinge_x"] / d  # in reference lengths, since M is normalised by d
    hinge = []
    for i, clock in enumerate(meta["canard_clock"]):
        c = comp[f"CANARD{i}"]
        a = (0.0, math.cos(math.radians(clock)), math.sin(math.radians(clock)))
        P = (hx, 0.0, 0.0)
        F, M = c["F"], c["M"]
        PxF = (P[1] * F[2] - P[2] * F[1], P[2] * F[0] - P[0] * F[2], P[0] * F[1] - P[1] * F[0])
        hinge.append(sum((M[k] - PxF[k]) * a[k] for k in range(3)))
        # normal force of the panel along its own plate normal (clock + 90 deg)
    res["hinge_coeff"] = hinge

    tot_F = [sum(comp[m]["F"][k] for m in MARKERS) for k in range(3)]
    tot_M = [sum(comp[m]["M"][k] for m in MARKERS) for k in range(3)]
    res["total"] = dict(F=tot_F, M=tot_M)
    res["roll"] = dict(canards=sum(comp[f"CANARD{i}"]["M"][0] for i in range(4)),
                       fins=sum(comp[f"FIN{i}"]["M"][0] for i in range(4)),
                       body=comp["BODY"]["M"][0])
    # convergence: spread of total CFz and roll over the last 10% of iterations
    tail = hist[-max(len(hist) // 10, 5):]
    def spread(name):
        vals = [sum(r.get(f"{name}({m})", 0.0) for m in MARKERS) for r in tail]
        return max(vals) - min(vals)
    res["conv"] = dict(
        rms_density=last.get("rms[Rho]", float("nan")),
        iters_used=len(hist),
        dCFz=spread("CFz"),
        dCMx=spread("CMx"),
    )
    (case_dir / "result.json").write_text(json.dumps(res, indent=2))
    return res


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", required=True)
    ap.add_argument("--level", default="medium")
    ap.add_argument("--np", type=int, default=8)
    ap.add_argument("--iter", type=int, default=2500)
    ap.add_argument("--reduce-only", action="store_true")
    a = ap.parse_args()
    case_dir = OUT / f"{a.case}_{a.level}"
    if not a.reduce_only:
        run(case_dir, a.np, a.iter)
    print(json.dumps(reduce(case_dir), indent=2))
