"""Check the canard module's newly-built Fusion geometry for interference, pairwise.

    python scripts/check_canard_interference_fusion.py            # print the script
    python scripts/check_canard_interference_fusion.py --write    # and into out/check_canard_interference_fusion_generated.py

MILESTONE M4 (interference-sweep half) of the canard-module Onshape -> Fusion migration
(docs/01-next-steps.md correction 44). This is the cross-check that geometry from separate
generators (M1's bay, M2's servo/bearing, M3's tube/panel/shaft, this session's placement
pass) doesn't just each verify correctly in isolation but actually FITS TOGETHER -- the
same distinction docs/01-next-steps.md:1508-1510 draws for the hand-built joints: "the
joint was added" and "the joint turns without collision" are different claims, and so are
"this part's volume is right" and "this part doesn't clash with its neighbour."

THE TECHNIQUE is docs/05-canard-module-build.md's own "reference as cutting tool" boolean
intersection, generalised to a pairwise sweep: `TemporaryBRepManager.copy()` both bodies,
`booleanOperation(..., IntersectionBooleanType)` them, and read the result's volume. Zero
(or a residual tolerance sliver, same class this project has measured before -- ~0.03 mm3
on Onshape's own reference geometry, docs/05:1296-1307) means no interference. Anything
larger is real.

NOT EXHAUSTIVE. A full pairwise sweep over every body in the document is O(n^2) and mostly
answers questions nobody is asking (Panel0 obviously does not touch Shaft2). This checks
only the pairs that are physically adjacent by design, four quadrants each:

  servo   vs bay       -- does the servo actually fit the tray/window cut for it
  bearing vs bay       -- does the bearing clear the collar (or sit in its designed reach)
  bearing vs tube      -- the wall bore seat: nominal-on-nominal should read ~0, not a
                          real interference (both cut at the same wall_bore_dia)
  shaft   vs tube      -- the shaft passing through the wall bore, running clearance
  shaft   vs bearing   -- the journal inside the bearing bore, running clearance
  panel   vs shaft      -- tang inside its slot: bonded, not unioned, and the slot is the
                          tang plus a bond line on every face, so this should read ~0
  panel   vs tube       -- the panel root's 0.5 mm standoff off the tube OD
  servo   vs bearing    -- the coupling gap between servo output face and bearing inboard

This is a READ-ONLY check: every comparison operates on temporary COPIES
(`TemporaryBRepManager.copy()`), never the real bodies in the document, so running it
cannot alter the model.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.fusion_common import FUSION_PRELUDE

OUT = Path(__file__).resolve().parents[1] / "out" / "check_canard_interference_fusion_generated.py"

# A real interference has to displace material a print/machining process could feel.
# Everything below this is the same residual-tolerance class docs/05 already measured on
# Onshape's own as-modelled reference geometry (~0.03 mm3, 6 pairs) -- not a target chosen
# for this check, a ceiling copied from the last time this project asked the same question.
INTERFERENCE_TOLERANCE_MM3 = 0.05


def emit() -> str:
    return f'''"""GENERATED by scripts/check_canard_interference_fusion.py -- do not edit this
file. Regenerate rather than patch.

Read-only: every comparison runs on temporary copies, never the real document bodies.
"""

{FUSION_PRELUDE}

TOLERANCE_MM3 = {INTERFERENCE_TOLERANCE_MM3}


def _body(comp, name):
    for b in comp.bRepBodies:
        if b.name == name:
            return b
    raise ValueError("no body named %r in %r" % (name, comp.name))


def _comp(root, name):
    for o in root.occurrences:
        if o.component.name == name:
            return o.component
    raise ValueError("no component named %r" % name)


def _overlap_mm3(tbm, body_a, body_b):
    a = tbm.copy(body_a)
    b = tbm.copy(body_b)
    if not tbm.booleanOperation(a, b, adsk.fusion.BooleanTypes.IntersectionBooleanType):
        return 0.0
    acc = adsk.fusion.CalculationAccuracy.VeryHighCalculationAccuracy
    return a.getPhysicalProperties(acc).volume * 1e3


def run(_context: str):
    app = adsk.core.Application.get()
    des = adsk.fusion.Design.cast(app.activeProduct)
    root = des.rootComponent
    tbm = adsk.fusion.TemporaryBRepManager.get()

    bay = _body(_comp(root, "CanardBay"), "canard bay")
    tube = _body(_comp(root, "Tube"), "tube")
    servo_comp = _comp(root, "Servo")
    bearing_comp = _comp(root, "Bearing")

    results = []
    flagged = []

    def check(label, body_a, body_b):
        v = _overlap_mm3(tbm, body_a, body_b)
        results.append((label, v))
        print("  %-28s %10.4f mm3  (tol %.3f)" % (label, v, TOLERANCE_MM3))
        if v > TOLERANCE_MM3:
            flagged.append("%s: %.4f mm3" % (label, v))

    for q in range(4):
        servo_body = _body(servo_comp, "servo body q%d" % q)
        bearing_body = _body(bearing_comp, "bearing q%d" % q)
        shaft = _body(_comp(root, "Shaft%d" % q), "shaft")
        panel = _body(_comp(root, "Panel%d" % q), "panel")

        check("servo q%d vs bay" % q, servo_body, bay)
        check("bearing q%d vs bay" % q, bearing_body, bay)
        check("bearing q%d vs tube" % q, bearing_body, tube)
        check("shaft q%d vs tube" % q, shaft, tube)
        check("shaft q%d vs bearing q%d" % (q, q), shaft, bearing_body)
        check("panel q%d vs shaft q%d" % (q, q), panel, shaft)
        check("panel q%d vs tube" % q, panel, tube)
        check("servo q%d vs bearing q%d" % (q, q), servo_body, bearing_body)

    print("\\n  %d pairs checked, %d over %.3f mm3 tolerance" \\
          % (len(results), len(flagged), TOLERANCE_MM3))
    if flagged:
        raise ValueError("INTERFERENCE FOUND: " + "; ".join(flagged))
    print("  OK -- no interference over tolerance in any checked pair")
'''


def main() -> None:
    text = emit()
    print(text)
    if "--write" in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"\n# written to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
