"""Check the canard module's Fusion geometry for interference AT DRIVEN HINGE ANGLES, not
just at rest.

    python scripts/check_canard_interference_driven_fusion.py            # print the script
    python scripts/check_canard_interference_driven_fusion.py --write    # and into out/check_canard_interference_driven_fusion_generated.py

MILESTONE M6 checklist item 2 (docs/01-next-steps.md correction 49's own open item, restated
in the M6 checklist): correction 49's 8-degree-driven interference sweep was done by hand,
ad hoc, covering three pairs (shaft-vs-bay, panel-vs-bay, panel-vs-tube) at exactly one
angle. This promotes that to a real, checked-in, drive-angle-parameterised script, and widens
both the pair list and the angle list -- "consider running it at a few more angles than just
0/8" was correction 49's own stated gap.

WHY THIS IS A DIFFERENT CHECK FROM scripts/check_canard_interference_fusion.py (M4), NOT A
DUPLICATE: that script reads bodies through `component.bRepBodies`, which is LOCAL geometry
and does not reflect a joint's occurrence-level transform -- it can only ever show the
static, undriven shape, no matter what angle a joint claims to be at (fusion-mcp-gotchas.md).
This script reads through `occurrence.bRepBodies` (proxies) instead, after actually setting
each revolute joint's `rotationValue`, so it tests the thing the shaft/panel really do:
sweep through the deflection range and pass through it, not just sit at zero without
touching anything.

ANGLES: 0, +/-4, +/-8 deg -- deg matches design/configure.py's DEFLECTION_LIMIT_DEG (the
whole commanded range, both directions) and 0/+lim/-lim/0 is the same order
scripts/canard_sweep.py already used on the Onshape side; +/-4 is the "a few more points"
correction 49 asked for. The model is reset to 0 deg at the end of the same script run --
no screenshot is needed mid-sweep (this is a numeric check, not the motion-check screenshot
correction 43/49 required), so unlike make_canard_joints_fusion.py's drive/reset pair this
does not need to split across two script executions.

PAIRS CHECKED, per quadrant, per angle -- only ones a hinge rotation can actually change.
Anything static-vs-static (servo-vs-bay, servo-vs-bearing, bearing-vs-bay, bearing-vs-tube)
never moves relative to itself as the shaft turns and is already covered once, at rest, by
the M4 sweep -- rechecking it at every angle would answer a question nobody is asking, the
same discipline the M4 script's own docstring states for skipping non-adjacent pairs:

  shaft  vs bay     -- does the shaft body (tang boss + spline socket) clear the bay collar
                       through the swing, not just at rest
  shaft  vs tube     -- the wall bore running clearance, through the swing
  shaft  vs bearing  -- the journal inside the bearing bore; rotation is about the shaft's
                       own axis so this should not change with angle, checked as a sanity
                       invariant rather than because it is expected to move
  panel  vs bay      -- the panel root sweeping past the printed bay's own outer envelope
  panel  vs tube      -- the panel root's standoff off the tube OD, through the swing
  panel  vs shaft      -- own-quadrant tang-in-slot; the rigid joint means this is a second
                       invariant check (should read the same at every angle, since shaft and
                       panel move together), not a pair expected to open up or close

This is READ-ONLY: every comparison operates on temporary COPIES of OCCURRENCE PROXIES
(never the real bodies), so running it cannot leave the model anywhere but back at 0 deg.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.fusion_common import FUSION_PRELUDE

OUT = Path(__file__).resolve().parents[1] / "out" / "check_canard_interference_driven_fusion_generated.py"

# Same ceiling as the at-rest M4 sweep (scripts/check_canard_interference_fusion.py) --
# a real interference has to displace material a print/machining process could feel, and
# this project has already measured what a residual, not-real, tolerance sliver reads like.
INTERFERENCE_TOLERANCE_MM3 = 0.05

DRIVE_ANGLES_DEG = (0.0, 4.0, 8.0, -4.0, -8.0, 0.0)


def emit() -> str:
    angles_repr = ", ".join("%g" % a for a in DRIVE_ANGLES_DEG)
    return f'''"""GENERATED by scripts/check_canard_interference_driven_fusion.py -- do not
edit this file. Regenerate rather than patch.

Read-only: every comparison runs on temporary copies of occurrence proxies, never the real
document bodies. Drives the 4 revolute hinge joints through {angles_repr} deg and resets to
0 deg before finishing, in this same script run.
"""

{FUSION_PRELUDE}

TOLERANCE_MM3 = {INTERFERENCE_TOLERANCE_MM3}
DRIVE_ANGLES_DEG = ({angles_repr})


def _occ(root, name):
    for o in root.occurrences:
        if o.component.name == name:
            return o
    raise ValueError("no occurrence named %r" % name)


def _proxy(occ, name):
    for b in occ.bRepBodies:
        if b.name == name:
            return b
    raise ValueError("no body named %r in occurrence %r" % (name, occ.component.name))


def _overlap_mm3(tbm, body_a, body_b):
    a = tbm.copy(body_a)
    b = tbm.copy(body_b)
    if not tbm.booleanOperation(a, b, adsk.fusion.BooleanTypes.IntersectionBooleanType):
        return 0.0
    acc = adsk.fusion.CalculationAccuracy.VeryHighCalculationAccuracy
    return a.getPhysicalProperties(acc).volume * 1e3


def _revolute(root, shaft_name):
    for j in root.asBuiltJoints:
        names = {{j.occurrenceOne.component.name, j.occurrenceTwo.component.name}}
        if names == {{shaft_name, "Tube"}}:
            rvm = adsk.fusion.RevoluteJointMotion.cast(j.jointMotion)
            if rvm is not None:
                return rvm
    raise ValueError("no revolute joint found for %s-Tube" % shaft_name)


def run(_context: str):
    app = adsk.core.Application.get()
    des = adsk.fusion.Design.cast(app.activeProduct)
    root = des.rootComponent
    tbm = adsk.fusion.TemporaryBRepManager.get()

    bay_occ = _occ(root, "CanardBay")
    tube_occ = _occ(root, "Tube")
    bearing_occ = _occ(root, "Bearing")
    bay = _proxy(bay_occ, "canard bay")
    tube = _proxy(tube_occ, "tube")

    revolutes = [_revolute(root, "Shaft%d" % q) for q in range(4)]

    results = []
    flagged = []

    def check(label, body_a, body_b):
        v = _overlap_mm3(tbm, body_a, body_b)
        results.append((label, v))
        print("  %-32s %10.4f mm3  (tol %.3f)" % (label, v, TOLERANCE_MM3))
        if v > TOLERANCE_MM3:
            flagged.append("%s: %.4f mm3" % (label, v))

    for angle_deg in DRIVE_ANGLES_DEG:
        for rvm in revolutes:
            rvm.rotationValue = math.radians(angle_deg)
        readback = [math.degrees(rvm.rotationValue) for rvm in revolutes]
        for r in readback:
            if abs(r - angle_deg) > 1e-6:
                raise ValueError("revolute did not reach %.1f deg, read back %.4f"
                                 % (angle_deg, r))
        print("-- driven to %+.1f deg --" % angle_deg)

        for q in range(4):
            shaft_occ = _occ(root, "Shaft%d" % q)
            panel_occ = _occ(root, "Panel%d" % q)
            shaft = _proxy(shaft_occ, "shaft")
            panel = _proxy(panel_occ, "panel")
            bearing_body = _proxy(bearing_occ, "bearing q%d" % q)

            check("q%d %+.1fdeg shaft vs bay" % (q, angle_deg), shaft, bay)
            check("q%d %+.1fdeg shaft vs tube" % (q, angle_deg), shaft, tube)
            check("q%d %+.1fdeg shaft vs bearing" % (q, angle_deg), shaft, bearing_body)
            check("q%d %+.1fdeg panel vs bay" % (q, angle_deg), panel, bay)
            check("q%d %+.1fdeg panel vs tube" % (q, angle_deg), panel, tube)
            check("q%d %+.1fdeg panel vs shaft" % (q, angle_deg), panel, shaft)

    for rvm in revolutes:
        rvm.rotationValue = 0.0
    for rvm in revolutes:
        if abs(math.degrees(rvm.rotationValue)) > 1e-6:
            raise ValueError("a revolute joint did not reset to 0 deg")
    print("\\n  all 4 revolute joints reset to 0 deg")

    print("\\n  %d pairs checked across %d angles, %d over %.3f mm3 tolerance"
          % (len(results), len(DRIVE_ANGLES_DEG), len(flagged), TOLERANCE_MM3))
    if flagged:
        raise ValueError("INTERFERENCE FOUND: " + "; ".join(flagged))
    print("  OK -- no interference over tolerance in any checked pair, at any driven angle")
'''


def main() -> None:
    text = emit()
    print(text)
    if "--write" in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"\n# written to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
