"""Cross-check the new native Fusion canard-module geometry (M1-M5) against the OLD HIDDEN
28-BODY REBUILD it is about to replace -- a second interference oracle, independent of the
generators' own analytic verify() checks.

    python scripts/check_canard_rebuild_cross_check_fusion.py            # print the script
    python scripts/check_canard_rebuild_cross_check_fusion.py --write    # and into out/

MILESTONE M6 checklist item 1 (docs/01-next-steps.md correction 44's migration plan,
restated after correction 49): M4/correction 48 deferred this exact check ("this checks the
newly-generated geometry against itself only, not against the existing hidden 28-body
rebuild as a second oracle... worth doing before M6's cutover, not done here"), and it is
the last thing standing between "the new build looks right on its own" and actually deleting
`Onshape_reference` plus the hidden rebuild in M6 item 3.

WHAT THE HIDDEN REBUILD IS: 28 bodies sitting directly in the Fusion document's ROOT
component (not in any occurrence), all with their lightbulb OFF -- `tube`, 4x `canard_0`
(quadrant pattern-copy naming, "canard_0 (1)"/"(2)"/"(3)"), 4x `shaft_0`, 4x `bearing_0`,
4x `servo_0`, `bay`, 8x `retainer_0`/`retainer_1` (2 rows x 4 quadrants), plus
`pass_through_plate` and `aft_gas_seal` (the two access-bulkhead parts, built and reconciled
separately -- out of scope here, this migration's six generators never touched them).
Correction 40 already reconciled this rebuild's tube/bay/servo/bearing bodies against
`Onshape_reference` (the STEP import) to near-zero difference, so it is itself a trusted,
already-verified oracle -- not the thing under test.

MATCHING IS BY MEASURED POSITION, NOT BY NAME. The rebuild's "(1)"/"(2)"/"(3)" suffixes are
Onshape's own circular-pattern naming and say nothing about which quadrant a body is
actually AT -- the same reasoning M6 item 1's own sibling checks in this migration have
used throughout ("measured, not assumed"). Each old body's centre-of-mass angle about Z is
read back and rounded to the nearest quadrant (0/90/180/270 deg); retainer bars are further
split by Z into two rows. New parts are already unambiguous (`Panel0..3`, `Shaft0..3`, one
`Bearing`/`Servo` component with per-quadrant-named bodies), so only the OLD side needs this
step.

THE TECHNIQUE is docs/05's own "reference as cutting tool" boolean, applied both directions:
for each corresponding (new, old) pair, `vol(new - old) + vol(old - new)` is the volume that
is in exactly one of the two shapes -- zero (or a residual-tolerance sliver, the same class
this project has measured before between two independently-authored representations of the
same design) means the two builds agree; anything larger is a real geometric disagreement
between them and would need explaining before the old rebuild can be deleted. The servo is
UNIONED first on each new side (new Servo splits case+flange/spline/lower-boss into 3
bodies per quadrant; the old rebuild's servo_0 is one merged body) so the comparison is
apples to apples.

`pass_through_plate` and `aft_gas_seal` are intentionally NOT compared -- they were never
part of this migration's six generators (M1-M5 built bay/servo/bearing/tube/panel/shaft
only) and have no corresponding new-side body to compare against.

READ-ONLY: every comparison operates on temporary COPIES, never the real document bodies.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.fusion_common import FUSION_PRELUDE

OUT = Path(__file__).resolve().parents[1] / "out" / "check_canard_rebuild_cross_check_fusion_generated.py"

# Two independently-authored builds of the same design are not expected to reproduce
# coincident faces to zero (docs/01-next-steps.md correction 40 measured this exact class of
# residual once already, ~0.02-0.03 mm3, between the old rebuild and the STEP-imported
# reference). This is deliberately looser than the same-generator-family interference
# tolerances (0.05 mm3) used elsewhere in this migration, for that reason.
AGREEMENT_TOLERANCE_MM3 = 1.0


def emit() -> str:
    return f'''"""GENERATED by scripts/check_canard_rebuild_cross_check_fusion.py -- do not
edit this file. Regenerate rather than patch.

Read-only: every comparison runs on temporary copies, never the real document bodies.
"""

{FUSION_PRELUDE}

TOLERANCE_MM3 = {AGREEMENT_TOLERANCE_MM3}


def _occ(root, name):
    for o in root.occurrences:
        if o.component.name == name:
            return o
    raise ValueError("no occurrence named %r" % name)


def _new_body(comp, name):
    for b in comp.bRepBodies:
        if b.name == name:
            return b
    raise ValueError("no body named %r in %r" % (name, comp.name))


def _quadrant_of(cx, cy):
    ang = math.degrees(math.atan2(cy, cx)) % 360.0
    return int(round(ang / 90.0)) % 4


def _old_bodies_by_family(root):
    """Group the 28 hidden root-level bodies by base name (Onshape pattern-copy suffix
    " (n)" stripped), each tagged with its measured quadrant (0/90/180/270) and Z.
    """
    import re
    fams = {{}}
    for b in root.bRepBodies:
        m = re.match(r"^(.*?)(?:\\s*\\((\\d+)\\))?$", b.name)
        base = m.group(1)
        pp = b.physicalProperties
        cx, cy, cz = pp.centerOfMass.x, pp.centerOfMass.y, pp.centerOfMass.z
        q = _quadrant_of(cx, cy)
        fams.setdefault(base, []).append({{"body": b, "quadrant": q, "z": cz}})
    return fams


def _symdiff_mm3(tbm, body_a, body_b):
    fwd = tbm.copy(body_a)
    tool = tbm.copy(body_b)
    if not tbm.booleanOperation(fwd, tool, adsk.fusion.BooleanTypes.DifferenceBooleanType):
        raise ValueError("forward difference did not take")
    acc = adsk.fusion.CalculationAccuracy.VeryHighCalculationAccuracy
    fwd_v = fwd.getPhysicalProperties(acc).volume * 1e3

    rev = tbm.copy(body_b)
    tool2 = tbm.copy(body_a)
    if not tbm.booleanOperation(rev, tool2, adsk.fusion.BooleanTypes.DifferenceBooleanType):
        raise ValueError("reverse difference did not take")
    rev_v = rev.getPhysicalProperties(acc).volume * 1e3

    return fwd_v + rev_v


def _union_temp(tbm, bodies):
    acc = adsk.fusion.CalculationAccuracy.VeryHighCalculationAccuracy
    result = tbm.copy(bodies[0])
    for b in bodies[1:]:
        if not tbm.booleanOperation(result, tbm.copy(b), adsk.fusion.BooleanTypes.UnionBooleanType):
            raise ValueError("servo union did not take")
    return result


def run(_context: str):
    app = adsk.core.Application.get()
    des = adsk.fusion.Design.cast(app.activeProduct)
    root = des.rootComponent
    tbm = adsk.fusion.TemporaryBRepManager.get()

    old = _old_bodies_by_family(root)

    def old_at(family, quadrant, z_row=None):
        members = old[family]
        cand = [m for m in members if m["quadrant"] == quadrant]
        if z_row is not None and len(cand) > 1:
            cand = sorted(cand, key=lambda m: m["z"])
            cand = [cand[z_row]]
        if len(cand) != 1:
            raise ValueError("expected exactly 1 %r body at quadrant %d (row %r), found %d"
                             % (family, quadrant, z_row, len(cand)))
        return cand[0]["body"]

    results = []
    flagged = []

    def check(label, body_a, body_b):
        v = _symdiff_mm3(tbm, body_a, body_b)
        results.append((label, v))
        print("  %-28s %10.4f mm3  (tol %.3f)" % (label, v, TOLERANCE_MM3))
        if v > TOLERANCE_MM3:
            flagged.append("%s: %.4f mm3" % (label, v))

    # -- singletons: tube, bay --
    new_tube = _new_body(_occ(root, "Tube").component, "tube")
    check("tube", new_tube, old["tube"][0]["body"])

    new_bay = _new_body(_occ(root, "CanardBay").component, "canard bay")
    check("bay", new_bay, old["bay"][0]["body"])

    # -- per-quadrant: panel, shaft, bearing, servo (unioned) --
    bearing_comp = _occ(root, "Bearing").component
    servo_comp = _occ(root, "Servo").component
    for q in range(4):
        panel = _new_body(_occ(root, "Panel%d" % q).component, "panel")
        check("panel q%d vs canard_0" % q, panel, old_at("canard_0", q))

        shaft = _new_body(_occ(root, "Shaft%d" % q).component, "shaft")
        check("shaft q%d vs shaft_0" % q, shaft, old_at("shaft_0", q))

        bearing = _new_body(bearing_comp, "bearing q%d" % q)
        check("bearing q%d vs bearing_0" % q, bearing, old_at("bearing_0", q))

        servo_bodies = [
            _new_body(servo_comp, "servo body q%d" % q),
            _new_body(servo_comp, "servo spline q%d" % q),
            _new_body(servo_comp, "servo boss q%d" % q),
        ]
        servo_union = _union_temp(tbm, servo_bodies)
        check("servo q%d (unioned) vs servo_0" % q, servo_union, old_at("servo_0", q))

    # -- retainer bars: 2 rows x 4 quadrants, matched by row (retainer_0 = low Z,
    # retainer_1 = high Z, per the measured z=60.630/87.130 split) --
    bay_comp = _occ(root, "CanardBay").component
    for q in range(4):
        for row, family in ((0, "retainer_0"), (1, "retainer_1")):
            new_bar = _new_body(bay_comp, "retainer bar q%dr%d" % (q, row))
            check("retainer q%dr%d vs %s" % (q, row, family), new_bar, old_at(family, q))

    print("\\n  %d pairs checked, %d over %.3f mm3 tolerance"
          % (len(results), len(flagged), TOLERANCE_MM3))
    if flagged:
        raise ValueError("DISAGREEMENT FOUND: " + "; ".join(flagged))
    print("  OK -- new build agrees with the old hidden 28-body rebuild on every pair")
'''


def main() -> None:
    text = emit()
    print(text)
    if "--write" in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"\n# written to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
