"""Generate the Fusion 360 script that builds the KST X08 Plus servo, from
design/packaging.py.

    python scripts/make_servo_cad_fusion.py            # print the script
    python scripts/make_servo_cad_fusion.py --write    # and into out/make_servo_cad_fusion_generated.py

MILESTONE M2 (first half) of the canard-module Onshape -> Fusion migration
(docs/01-next-steps.md correction 44). This ports `scripts/make_servo_cad.py`'s geometry
into `scripts/fusion_common.py`'s temp-BRep pattern -- every feature there is a plain box
or cylinder along a single axis, so this is a direct, mechanical port with none of the
FeatureScript detours the bay needed.

FRAME, kept identical to `scripts/make_servo_cad.py`'s own (so a future placement pass can
reuse its reasoning unchanged): origin ON THE OUTPUT AXIS, on the case face the spline
emerges from. +Z is the direction the spline points, +X runs along the 23.5 mm case axis
away from the near end, +Y across the 8 mm width. In the module assembly this makes +Z
radially outward and the origin lands on the hinge axis at the wall -- placement (a future
milestone) is then pure translation/rotation, no offset arithmetic.

THREE BODIES, matching the Onshape original exactly: the case and its mounting flange are
one body (lug holes cut into it); the output spline is its own body, because it turns and
the case does not; the lower boss is a third, separate body, modelled as a KEEP-OUT rather
than structure -- see `scripts/make_servo_cad.py`'s own header for why (it comes off the
datasheet's side view, not a plan-view dimension, and needs confirming against a physical
part).

VERIFICATION. The Onshape original only PRINTS a bounding box for a human to eyeball; it
never asserts one (`main()`'s "expected:" line has no comparison in code). This generator's
own `verify()` makes that assertion for real -- the case+flange body's bounding box is
checked against the envelope it should occupy, with a tolerance, and fails loudly rather
than trusting a human to notice a mismatch printed to a terminal.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from design.packaging import SERVO_GEOMETRY, SERVOS
from scripts.fusion_common import FUSION_PRELUDE

MM = 1000.0
OUT = Path(__file__).resolve().parents[1] / "out" / "make_servo_cad_fusion_generated.py"

COMPONENT = "Servo"
SERVO_KEY = "kst_x08_plus"

# The lower boss is drawn on the datasheet's side view but not dimensioned in plan, so its
# extent along the case is scaled off that view -- carried forward unverified from
# scripts/make_servo_cad.py:44, not silently promoted to a measured number by this port.
BOSS_START_FROM_SHAFT_MM = 9.2

BBOX_TOLERANCE_MM = 0.01


def emit() -> str:
    g = SERVO_GEOMETRY[SERVO_KEY]

    x_near = -g.shaft_from_end * MM
    x_far = x_near + g.case_length * MM
    half_w = g.case_width * MM / 2.0
    env_near = x_near - (g.envelope_length * MM - g.case_length * MM) / 2.0
    env_far = env_near + g.envelope_length * MM
    lug_x = [env_near + 1.5, env_far - 1.5]
    lug_y = g.lug_hole_pitch_across * MM / 2.0

    # Self-check, same one make_servo_cad.py:76 makes: the datasheet dimensions the shaft
    # 7.64 mm from the lug-hole line. If this fires, the envelope/case/shaft numbers have
    # stopped agreeing.
    assert abs(abs(lug_x[0]) - 7.64) < 0.01, f"lug line at {lug_x[0]}, expected -7.64"

    case_z0, case_z1 = -g.case_height * MM, 0.0
    flange_z0 = -(g.flange_from_top * MM + g.flange_thickness * MM)
    flange_z1 = -g.flange_from_top * MM
    over = 1.0
    lug_z0 = -(g.flange_from_top * MM - over)
    lug_z1 = -(g.flange_from_top * MM + g.flange_thickness * MM + over)
    boss_z0, boss_z1 = -g.depth_from_top * MM, -g.case_height * MM

    return f'''"""GENERATED by scripts/make_servo_cad_fusion.py -- do not edit this file.

Every number below comes from design/packaging.py. Regenerate rather than patch.

Servo body   X {x_near:.3f} .. {x_far:.3f}, Y +/-{half_w:.3f}, Z {case_z0:.3f} .. 0.000 (case),
             flange Z {flange_z0:.3f} .. {flange_z1:.3f}, envelope X {env_near:.3f} .. {env_far:.3f}
Spline       dia {g.spline_dia * MM:.3f}, Z 0.000 .. {g.shaft_proud_of_top * MM:.3f}
Boss         X {BOSS_START_FROM_SHAFT_MM:.3f} .. {x_far:.3f}, Z {boss_z0:.3f} .. {boss_z1:.3f} (keep-out, not structure)
Mass to assign, if wired up later: {SERVOS[SERVO_KEY].mass * 1000:.1f} g
"""

{FUSION_PRELUDE}

COMPONENT = {COMPONENT!r}

X_NEAR = {x_near:.4f}
X_FAR = {x_far:.4f}
HALF_W = {half_w:.4f}
ENV_NEAR = {env_near:.4f}
ENV_FAR = {env_far:.4f}
LUG_X = [{lug_x[0]:.4f}, {lug_x[1]:.4f}]
LUG_Y = {lug_y:.4f}
LUG_HOLE_R = {g.lug_hole_dia * MM / 2.0:.4f}
LUG_HOLE_2_R = {g.lug_hole_2_dia * MM / 2.0:.4f}
LUG_Z0 = {lug_z0:.4f}
LUG_Z1 = {lug_z1:.4f}

CASE_Z0 = {case_z0:.4f}
FLANGE_Z0 = {flange_z0:.4f}
FLANGE_Z1 = {flange_z1:.4f}

SPLINE_R = {g.spline_dia * MM / 2.0:.4f}
SPLINE_Z1 = {g.shaft_proud_of_top * MM:.4f}

BOSS_X0 = {BOSS_START_FROM_SHAFT_MM:.4f}
BOSS_Z0 = {boss_z0:.4f}
BOSS_Z1 = {boss_z1:.4f}

CASE_LENGTH = {g.case_length * MM:.4f}
CASE_WIDTH = {g.case_width * MM:.4f}
CASE_HEIGHT = {g.case_height * MM:.4f}
FLANGE_THICKNESS = {g.flange_thickness * MM:.4f}
DEPTH_FROM_TOP = {g.depth_from_top * MM:.4f}
SHAFT_FROM_END = {g.shaft_from_end * MM:.4f}
ENVELOPE_LENGTH = {g.envelope_length * MM:.4f}

BBOX_TOL = {BBOX_TOLERANCE_MM:.4f}


def run(_context: str):
    app = adsk.core.Application.get()
    des = adsk.fusion.Design.cast(app.activeProduct)
    root = des.rootComponent
    tbm = adsk.fusion.TemporaryBRepManager.get()

    occ, has_bodies = _get_or_create_component(root, COMPONENT)
    if has_bodies:
        print("%s already holds %d bodies -- verifying rather than rebuilding"
              % (COMPONENT, occ.component.bRepBodies.count))
        verify(occ.component)
        return
    comp = occ.component

    made = []

    # ---- 1. case + flange, less the six lug holes ----
    case = _box(tbm, (X_NEAR + X_FAR) / 2.0, 0.0, (CASE_Z0 + 0.0) / 2.0,
                CASE_LENGTH, CASE_WIDTH, CASE_HEIGHT)
    flange = _box(tbm, (ENV_NEAR + ENV_FAR) / 2.0, 0.0, (FLANGE_Z0 + FLANGE_Z1) / 2.0,
                  ENVELOPE_LENGTH, CASE_WIDTH, FLANGE_THICKNESS)
    _union(tbm, case, flange, "flange")

    for x in LUG_X:
        for y in (-LUG_Y, LUG_Y):
            hole = _cyl(tbm, x, y, LUG_Z0, LUG_Z1, LUG_HOLE_R)
            _cut(tbm, case, hole, "lug hole")
        big = _cyl(tbm, x, 0.0, LUG_Z0, LUG_Z1, LUG_HOLE_2_R)
        _cut(tbm, case, big, "lug dowel hole")

    made.append(("servo body", case))

    # ---- 2. the output spline, its own body -- it turns and the case does not ----
    made.append(("servo spline", _cyl(tbm, 0.0, 0.0, 0.0, SPLINE_Z1, SPLINE_R)))

    # ---- 3. the lower boss, a keep-out volume, its own body ----
    made.append(("servo boss", _box(tbm, (BOSS_X0 + X_FAR) / 2.0, 0.0,
                                     (BOSS_Z0 + BOSS_Z1) / 2.0,
                                     X_FAR - BOSS_X0, CASE_WIDTH, BOSS_Z1 - BOSS_Z0)))

    _inject(comp, made)
    print("built %d bodies in %s" % (len(made), COMPONENT))
    verify(comp)


def verify(comp):
    """Bounding box of the case+flange body against the envelope it should occupy -- a
    REAL assertion, where scripts/make_servo_cad.py's own script only ever printed this
    for a human to eyeball.
    """
    bad = []
    body = None
    for b in comp.bRepBodies:
        if b.name == "servo body":
            body = b
    if body is None:
        raise ValueError("VERIFY FAILED: servo body is missing")

    bb = body.boundingBox
    got = {{
        "lowX": bb.minPoint.x * 10.0, "highX": bb.maxPoint.x * 10.0,
        "lowY": bb.minPoint.y * 10.0, "highY": bb.maxPoint.y * 10.0,
        "lowZ": bb.minPoint.z * 10.0, "highZ": bb.maxPoint.z * 10.0,
    }}
    want = {{
        "lowX": ENV_NEAR, "highX": ENV_FAR,
        "lowY": -HALF_W, "highY": HALF_W,
        # The CASE is deeper (CASE_HEIGHT) than the flange (FLANGE_Z0), so it sets the
        # low-Z extent, not the flange -- a bounding box takes the deepest of the two.
        "lowZ": CASE_Z0, "highZ": 0.0,
    }}
    for k, wv in want.items():
        gv = got[k]
        print("  %-6s %10.4f mm  want %10.4f  delta %+8.4f  (tol %.3f)"
              % (k, gv, wv, gv - wv, BBOX_TOL))
        if abs(gv - wv) > BBOX_TOL:
            bad.append("%s is %+.4f mm out" % (k, gv - wv))

    if bad:
        raise ValueError("VERIFY FAILED: " + "; ".join(bad))
    print("  OK")
'''


def main() -> None:
    text = emit()
    print(text)
    if "--write" in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"\n# written to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
