"""Build the two recovery bulkheads (aft gas seal, internal bulkhead) as native Fusion
geometry, from design/seal.py -- porting scripts/make_bulkhead_cad.py (correction 34) off
Onshape.

    python scripts/make_seal_cad_fusion.py            # print the script
    python scripts/make_seal_cad_fusion.py --write    # and into out/make_seal_cad_fusion_generated.py

WHY THIS EXISTS NOW, not as part of the original six-generator migration plan (correction
44): `Onshape_reference`'s hidden 28-body Fusion rebuild (correction 40) carries these two
parts alongside the six that M1-M5 already ported -- and asked what should happen to them
at M6's cutover, the answer was "migrate them too", not "delete them with nothing standing
in for them." A part that is not modelled cannot collide with anything (correction 18's own
lesson, restated a fourth time).

WHAT GETS BUILT, same scope as make_bulkhead_cad.py, deliberately only what the model
specifies: the aft gas seal (dia 74.8 x 4.8 G-10, 2x dia 4.0 feed-through, 2x dia 5.5
U-bolt) and the internal bulkhead (dia 74.8 x 4.8, 1x dia 6.0 conduit, 2x dia 5.5 U-bolt).
The charge well, U-bolt itself, backing plate, epoxy fillet and feed-through RTV are still
not here -- same caveat the Onshape original states.

FRAME. The aft gas seal is built DIRECTLY IN THE MODULE'S GLOBAL FRAME (not a local frame
placed later, M4-style) because the tube's own Z span is already known and fixed in this
document (Z 0.000 forward face -> 142.9200 aft face, confirmed by measuring the live Tube
body's bounding box rather than assumed): origin on the disc's AFT face, growing FORWARD,
so the disc spans Z [142.9200 - thickness, 142.9200]. This is the CanardBay precedent
(correction 45: "it was drawn in the module's own frame", no separate placement script
needed) applied to a flat part. The internal bulkhead is NOT placed -- it sits 240 mm
further aft in a recovery bay this project has never modelled, same reasoning
make_bulkhead_cad.py itself states -- and is built at its own local origin (Z [0, thickness]
at the document's shared root origin), the same "two independently-drawn parts both
defaulting to identity transform" state M2's servo/bearing were left in before M4 placed
them (correction 46).

VERIFIED the same way make_bulkhead_cad.py's own verify() does: volume against the analytic
disc-less-holes figure, to the same 0.01 mm3 tolerance -- "the only proof the holes actually
cut" (a solid disc and a drilled one differ by well under 1% of volume here, which no coarser
check would ever catch).
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from design import seal
from design.configure import baseline, evaluate
from scripts.fusion_common import FUSION_PRELUDE

OUT = Path(__file__).resolve().parents[1] / "out" / "make_seal_cad_fusion_generated.py"

VOLUME_TOLERANCE_MM3 = 0.01

# The module's aft face, read off the live Tube body's own bounding box (confirmed, not
# assumed) -- see docs/01-next-steps.md's own Z 142.900 figure, which this matches to the
# fourth decimal once the tube's real extrude depth is accounted for.
MODULE_AFT_FACE_MM = 142.92


def _disc_and_holes(r: seal.SealResult):
    b = r.bulkhead
    holes = [(h.name, h.x * 1000.0, h.y * 1000.0, h.diameter * 1000.0)
             for h in seal.hole_layout(r)]
    want = math.pi * b.radius**2 * b.thickness
    for h in seal.hole_layout(r):
        want -= math.pi * (h.diameter / 2.0) ** 2 * b.thickness
    return b.radius * 1000.0, b.thickness * 1000.0, holes, want * 1e9


def emit() -> str:
    ev = evaluate(baseline())
    seal_r, seal_t, seal_holes, seal_want = _disc_and_holes(seal.from_evaluation(ev))
    int_r, int_t, int_holes, int_want = _disc_and_holes(
        seal.internal_bulkhead_from_evaluation(ev))

    def holes_repr(holes):
        return ", ".join("(%r, %r, %r, %r)" % h for h in holes)

    return f'''"""GENERATED by scripts/make_seal_cad_fusion.py -- do not edit this file.
Regenerate rather than patch.

Builds AftGasSeal (in the module's global frame, aft face at Z {MODULE_AFT_FACE_MM:.4f})
and RecoveryInternalBulkhead (local frame, not placed -- the recovery bay is not modelled).
Idempotent: verifies rather than rebuilds if either component already has bodies.
"""

{FUSION_PRELUDE}

VOLUME_TOLERANCE_MM3 = {VOLUME_TOLERANCE_MM3!r}
AFT_FACE_MM = {MODULE_AFT_FACE_MM}

SEAL_RADIUS_MM = {seal_r!r}
SEAL_THICKNESS_MM = {seal_t!r}
SEAL_HOLES = [{holes_repr(seal_holes)}]
SEAL_WANT_MM3 = {seal_want!r}

INTERNAL_RADIUS_MM = {int_r!r}
INTERNAL_THICKNESS_MM = {int_t!r}
INTERNAL_HOLES = [{holes_repr(int_holes)}]
INTERNAL_WANT_MM3 = {int_want!r}

OVER_MM = 1.0


def _build_disc(tbm, cx, cy, z0, z1, radius, holes):
    """A disc from z0 to z1 (mm, z0 < z1) at (cx, cy), with each hole cut as its own
    overshooting cylinder -- same "separate cut per hole, overshoot both faces" discipline
    as the Onshape original (a REMOVE landing exactly on a face is degenerate)."""
    body = _cyl(tbm, cx, cy, z0, z1, radius)
    for (name, hx, hy, hd) in holes:
        tool = _cyl(tbm, cx + hx, cy + hy, z0 - OVER_MM, z1 + OVER_MM, hd / 2.0)
        _cut(tbm, body, tool, name)
    return body


def run(_context: str):
    app = adsk.core.Application.get()
    des = adsk.fusion.Design.cast(app.activeProduct)
    root = des.rootComponent
    tbm = adsk.fusion.TemporaryBRepManager.get()

    # -- Aft gas seal: module global frame, origin on the aft face, growing forward --
    seal_occ, seal_has_bodies = _get_or_create_component(root, "AftGasSeal")
    if not seal_has_bodies:
        z1 = AFT_FACE_MM
        z0 = AFT_FACE_MM - SEAL_THICKNESS_MM
        body = _build_disc(tbm, 0.0, 0.0, z0, z1, SEAL_RADIUS_MM, SEAL_HOLES)
        _inject(seal_occ.component, [("aft gas seal", body)])
        print("AftGasSeal: built, Z %.4f -> %.4f mm" % (z0, z1))
    else:
        print("AftGasSeal: already has bodies, verifying only")
    bad = _verify_volume(seal_occ.component, {{"aft gas seal": SEAL_WANT_MM3}}, VOLUME_TOLERANCE_MM3)

    # -- Internal bulkhead: local frame, NOT placed (no recovery bay modelled) --
    int_occ, int_has_bodies = _get_or_create_component(root, "RecoveryInternalBulkhead")
    if not int_has_bodies:
        body = _build_disc(tbm, 0.0, 0.0, 0.0, INTERNAL_THICKNESS_MM, INTERNAL_RADIUS_MM,
                           INTERNAL_HOLES)
        _inject(int_occ.component, [("recovery internal bulkhead", body)])
        print("RecoveryInternalBulkhead: built, local frame Z 0.0000 -> %.4f mm"
              % INTERNAL_THICKNESS_MM)
    else:
        print("RecoveryInternalBulkhead: already has bodies, verifying only")
    bad += _verify_volume(int_occ.component,
                          {{"recovery internal bulkhead": INTERNAL_WANT_MM3}},
                          VOLUME_TOLERANCE_MM3)

    if bad:
        raise ValueError("VERIFY FAILED: " + "; ".join(bad))
    print("  OK -- both bulkheads verified against analytic disc-less-holes volume")
'''


def main() -> None:
    text = emit()
    print(text)
    if "--write" in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"\n# written to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
