"""Generate the Fusion 360 script that wires the canard module's eight hinge joints, from
design/hinge.py's own description of the mechanism.

    python scripts/make_canard_joints_fusion.py            # print the script
    python scripts/make_canard_joints_fusion.py --write    # and into out/make_canard_joints_fusion_generated.py

MILESTONE M5 of the canard-module Onshape -> Fusion migration (docs/01-next-steps.md
correction 44). Every other generator in this migration derives dimensions from
design/*.py; this one does not need to -- a joint is a relationship between two ALREADY-
BUILT, ALREADY-VERIFIED, ALREADY-PLACED occurrences (M3's Panel0-3/Shaft0-3/Tube, M4's
placement pass), not new geometry, so there is nothing to derive. What this file needed
was not a number but a call shape, and that was retired in M0 (correction 44): a spike
against this exact document confirmed `AsBuiltJoint` creation, both rigid and revolute,
including driving motion, before this generator was written for real.

EIGHT JOINTS, mirroring the hand-built ones docs/01-next-steps.md correction 43 describes
for `Onshape_reference`, now against native Fusion geometry instead of a STEP import:
  * 4 RIGID joints, Shaft{{q}} <-> Panel{{q}} -- the tang bonded into its slot. Zero DOF,
    no geometry argument (`AsBuiltJoints.createInput(shaft, panel, None)`).
  * 4 REVOLUTE joints, Shaft{{q}} <-> Tube -- the hinge itself. Axis read directly off the
    shaft's own cylindrical face via `JointGeometry.createByCylinderOrConeFace`, exactly
    as the hand-built joints were: "axis read directly off the shaft's own cylindrical
    face" (correction 43). The shaft has THREE cylindrical faces at two different radii
    (the rod's outer surface, and the spline socket's bore, which is narrower and shorter)
    -- see fusion-mcp-gotchas.md's own warning about a stepped shaft's smaller-radius
    cylinder not being the hinge -- so this picks the LARGEST-AREA cylindrical face, not
    just the first one found.

AS-BUILT, NOT REGULAR, JOINTS -- same reasoning as correction 43's hand-built ones, and it
applies MORE strongly here, not less: a regular joint snaps the second occurrence to align
with picked geometry, which is exactly backwards when the geometry is already exactly
where the analytic model says it belongs (M4's placement pass, verified to 1e-6 degrees).
There is nothing to snap; an as-built joint freezes what is already correct.

IDEMPOTENT BY INSPECTION, NOT BY NAME. `AsBuiltJoint` objects are found again by checking
which two occurrences (by COMPONENT NAME, not object identity -- proxy objects from
different queries are not guaranteed to compare equal) a joint connects and what
`JointMotion` subtype it carries, not by a `.name` this generator sets itself -- after
correction 48's body-renaming discovery elsewhere in this migration, this file does not
assume ANY name assigned in the same transaction that creates an object will survive to a
later, separate script run, and joints were not spiked for that specific failure mode.
Checking real state is cheap and does not depend on the assumption being true.

VERIFICATION: existence, correct type, and correct occurrence pair for all eight: then the
motion check correction 43 and correction 39 before it both insist on -- "a joint that
added successfully and one that turns are different claims" -- driving all four revolute
joints to DRIVE_ANGLE_DEG so a screenshot can confirm it, in this same script. Resetting to
0 deg is a SEPARATE follow-up script (see main.py's docstring at the bottom) so a
screenshot can be taken in between the two, from outside this script's own transaction.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.fusion_common import FUSION_PRELUDE

OUT = Path(__file__).resolve().parents[1] / "out" / "make_canard_joints_fusion_generated.py"
RESET_OUT = Path(__file__).resolve().parents[1] / "out" / "reset_canard_joints_fusion_generated.py"

DRIVE_ANGLE_DEG = 8.0


def emit() -> str:
    return f'''"""GENERATED by scripts/make_canard_joints_fusion.py -- do not edit this file.

Wires (or verifies) the canard module's 8 hinge joints and drives the 4 revolute ones to
{DRIVE_ANGLE_DEG:.1f} deg for a motion-check screenshot. Run the paired
out/reset_canard_joints_fusion_generated.py afterward to put the mechanism back at 0.
"""

{FUSION_PRELUDE}

DRIVE_ANGLE_DEG = {DRIVE_ANGLE_DEG}


def _occ(root, name):
    for o in root.occurrences:
        if o.component.name == name:
            return o
    raise ValueError("no occurrence named %r" % name)


def _largest_cyl_face(body):
    """The hinge axis face -- LARGEST area, not just the first cylindrical face found.
    A stepped shaft has more than one cylinder (the rod's own OD, and the narrower,
    shorter spline socket bore); picking the wrong one silently hinges on the wrong axis.
    """
    faces = [f for f in body.faces if f.geometry.objectType.endswith("Cylinder")]
    if not faces:
        raise ValueError("no cylindrical face on body %r" % body.name)
    return max(faces, key=lambda f: f.area)


def _find_joint(root, name_a, name_b, motion_cls):
    """Find an existing AsBuiltJoint between the occurrences named `name_a`/`name_b`
    (either order) carrying a `motion_cls` JointMotion -- by inspecting live state, not
    by trusting a name this generator set itself. See the module docstring for why.
    """
    for j in root.asBuiltJoints:
        names = {{j.occurrenceOne.component.name, j.occurrenceTwo.component.name}}
        if names == {{name_a, name_b}} and motion_cls.cast(j.jointMotion) is not None:
            return j
    return None


def run(_context: str):
    app = adsk.core.Application.get()
    des = adsk.fusion.Design.cast(app.activeProduct)
    root = des.rootComponent

    tube_occ = _occ(root, "Tube")

    made_rigid = 0
    made_revolute = 0
    joints = []

    for q in range(4):
        shaft_name = "Shaft%d" % q
        panel_name = "Panel%d" % q
        shaft_occ = _occ(root, shaft_name)
        panel_occ = _occ(root, panel_name)

        rigid = _find_joint(root, shaft_name, panel_name, adsk.fusion.RigidJointMotion)
        if rigid is None:
            inp = root.asBuiltJoints.createInput(shaft_occ, panel_occ, None)
            inp.setAsRigidJointMotion()
            rigid = root.asBuiltJoints.add(inp)
            if rigid is None:
                raise ValueError("q%d rigid joint (shaft-panel) failed to create" % q)
            made_rigid += 1

        revolute = _find_joint(root, shaft_name, "Tube", adsk.fusion.RevoluteJointMotion)
        if revolute is None:
            shaft_body = shaft_occ.bRepBodies.item(0)
            face = _largest_cyl_face(shaft_body)
            geo = adsk.fusion.JointGeometry.createByCylinderOrConeFace(
                face, adsk.fusion.JointQuadrantAngleTypes.StartJointQuadrantAngleType,
                adsk.fusion.JointKeyPointTypes.MiddleKeyPoint)
            inp = root.asBuiltJoints.createInput(shaft_occ, tube_occ, geo)
            inp.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
            revolute = root.asBuiltJoints.add(inp)
            if revolute is None:
                raise ValueError("q%d revolute joint (shaft-tube) failed to create" % q)
            made_revolute += 1

        joints.append((q, rigid, revolute))

    print("joints: %d new rigid, %d new revolute (8 total expected across all quadrants)"
          % (made_rigid, made_revolute))

    bad = []
    for (q, rigid, revolute) in joints:
        if adsk.fusion.RigidJointMotion.cast(rigid.jointMotion) is None:
            bad.append("q%d rigid joint is not RigidJointMotion" % q)
        if adsk.fusion.RevoluteJointMotion.cast(revolute.jointMotion) is None:
            bad.append("q%d revolute joint is not RevoluteJointMotion" % q)
    if bad:
        raise ValueError("VERIFY FAILED: " + "; ".join(bad))
    print("  OK -- 8 joints present, correctly typed (4 rigid shaft-panel, "
          "4 revolute shaft-tube)")

    # ---- motion check: drive all 4 revolute joints, screenshot from outside this
    # script, reset in a SEPARATE follow-up script -- "a joint that added successfully
    # and one that turns are different claims" (docs/01-next-steps.md correction 43) ----
    for (q, rigid, revolute) in joints:
        rvm = adsk.fusion.RevoluteJointMotion.cast(revolute.jointMotion)
        rvm.rotationValue = math.radians(DRIVE_ANGLE_DEG)
        readback = math.degrees(rvm.rotationValue)
        print("  q%d revolute driven to %.4f deg" % (q, readback))
        if abs(readback - DRIVE_ANGLE_DEG) > 1e-6:
            raise ValueError("q%d revolute did not reach %.1f deg, read back %.4f"
                             % (q, DRIVE_ANGLE_DEG, readback))
    print("  all 4 revolute joints driven to %.1f deg -- screenshot before resetting"
          % DRIVE_ANGLE_DEG)
'''


def emit_reset() -> str:
    return f'''"""GENERATED by scripts/make_canard_joints_fusion.py -- do not edit this file.

Resets the canard module's 4 revolute hinge joints to 0 deg after the motion-check
screenshot. Run this only after confirming the driven-to-{DRIVE_ANGLE_DEG:.1f}-deg screenshot.
"""

{FUSION_PRELUDE}


def _occ(root, name):
    for o in root.occurrences:
        if o.component.name == name:
            return o
    raise ValueError("no occurrence named %r" % name)


def run(_context: str):
    app = adsk.core.Application.get()
    des = adsk.fusion.Design.cast(app.activeProduct)
    root = des.rootComponent

    reset = 0
    for q in range(4):
        shaft_name = "Shaft%d" % q
        found = None
        for j in root.asBuiltJoints:
            names = {{j.occurrenceOne.component.name, j.occurrenceTwo.component.name}}
            if names == {{shaft_name, "Tube"}}:
                rvm = adsk.fusion.RevoluteJointMotion.cast(j.jointMotion)
                if rvm is not None:
                    found = rvm
        if found is None:
            raise ValueError("no revolute joint found for %s-Tube" % shaft_name)
        found.rotationValue = 0.0
        readback = math.degrees(found.rotationValue)
        print("  q%d revolute reset to %.4f deg" % (q, readback))
        if abs(readback) > 1e-6:
            raise ValueError("q%d revolute did not reset to 0, read back %.4f" % (q, readback))
        reset += 1

    print("  OK -- %d revolute joints reset to 0 deg" % reset)
'''


def main() -> None:
    text = emit()
    print(text)
    reset_text = emit_reset()
    if "--write" in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        RESET_OUT.write_text(reset_text)
        print(f"\n# written to {OUT} and {RESET_OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
