"""Generate the Fusion 360 script that builds the canard hinge bearing, from
design/hinge.py.

    python scripts/make_bearing_cad_fusion.py            # print the script
    python scripts/make_bearing_cad_fusion.py --write    # and into out/make_bearing_cad_fusion_generated.py

MILESTONE M2 (second half) of the canard-module Onshape -> Fusion migration
(docs/01-next-steps.md correction 44). Ports `scripts/make_bearing_cad.py`'s geometry --
a hollow cylinder, bore over journal diameter by the design's running clearance -- into
`scripts/fusion_common.py`'s temp-BRep pattern. The Onshape original splits the OD and the
bore into two separate features to sidestep an Onshape-specific ambiguity (two concentric
circles in one sketch give two regions, and which one an extrude takes depends on a filter
flag); that ambiguity does not exist here, but the same two-step OD-then-cut structure is
kept anyway because it is simply the correct way to build an annulus with `_cyl` + `_cut`.

FRAME, matching `scripts/make_servo_cad.py`'s and chosen for the same reason: origin ON THE
HINGE AXIS, on the bearing's OUTBOARD face, +Z radially outward. That face is flush with
the tube OD, so in the module assembly the bearing's origin lands at R equal to the tube
outer radius -- a number a future placement pass can read directly, no offset arithmetic.

Modelled at NOMINAL bore, dia journal + BEARING_RUNNING_CLEARANCE -- not the journal
diameter itself, which was the exact defect `design/hinge.py`'s header describes (a dia 5
hole around a dia 5 shaft is not an interference and is invisible to every interference
check). And at NOMINAL OD, not the 0.030 mm supplied-oversize press-fit dimension, for the
same reason `scripts/make_bearing_cad.py:30-32` gives: modelling the oversize would make
the bearing read as interfering with its own seat in every clash check.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from design import hinge
from design.configure import baseline, build_vehicle
from design.packaging import SERVO_GEOMETRY
from scripts.fusion_common import FUSION_PRELUDE

MM = 1000.0
OUT = Path(__file__).resolve().parents[1] / "out" / "make_bearing_cad_fusion_generated.py"

COMPONENT = "Bearing"
VOLUME_TOLERANCE_MM3 = 0.01   # a plain annulus, axial bore -- exact, like the sled's plate


def stack() -> hinge.HingeStack:
    p = baseline()
    r = build_vehicle(p)
    return hinge.selected(r.diameter / 2.0, r.tubes[1].wall_thickness,
                          SERVO_GEOMETRY[p.servo])


def bore_dia(s: hinge.HingeStack) -> float:
    """The bore is the journal plus its running clearance, not the journal diameter --
    see the module docstring and design/hinge.py's own header for why that distinction
    is the entire reason this file exists."""
    return s.journal_dia + hinge.BEARING_RUNNING_CLEARANCE


def emit() -> str:
    s = stack()
    od = s.bearing_od * MM
    idia = bore_dia(s) * MM
    length = s.bearing_length * MM

    volume_mm3 = math.pi * ((od / 2.0) ** 2 - (idia / 2.0) ** 2) * length
    solid_slug_mm3 = math.pi * (od / 2.0) ** 2 * length

    return f'''"""GENERATED by scripts/make_bearing_cad_fusion.py -- do not edit this file.

Every number below comes from design/hinge.py. Regenerate rather than patch.

Bearing   OD {od:.3f} / bore {idia:.3f} (journal + running clearance) x {length:.3f} long
Volume    {volume_mm3:.4f} mm3 (annulus, exact)
Placement, once wired up: origin at R {s.bearing_outboard * MM:.3f} on the hinge axis,
+Z outward -- spans R {s.bearing_inboard * MM:.3f} .. {s.bearing_outboard * MM:.3f}
"""

{FUSION_PRELUDE}

COMPONENT = {COMPONENT!r}
OVER = 1.0   # mm, overshoot on the bore cut -- see fusion_common.py's header

OD = {od:.4f}
BORE_DIA = {idia:.4f}
LENGTH = {length:.4f}

VOLUME_MM3 = {volume_mm3:.4f}
VOLUME_TOLERANCE = {VOLUME_TOLERANCE_MM3:.4f}


def run(_context: str):
    app = adsk.core.Application.get()
    des = adsk.fusion.Design.cast(app.activeProduct)
    root = des.rootComponent
    tbm = adsk.fusion.TemporaryBRepManager.get()

    occ, has_bodies = _get_or_create_component(root, COMPONENT)
    if has_bodies:
        print("%s already holds %d bodies -- verifying rather than rebuilding"
              % (COMPONENT, occ.component.bRepBodies.count))
        verify(occ.component)
        return
    comp = occ.component

    # Grows INBOARD from the origin (-Z), so +Z stays the outward radial direction.
    body = _cyl(tbm, 0.0, 0.0, -LENGTH, 0.0, OD / 2.0)
    _cut(tbm, body, _cyl(tbm, 0.0, 0.0, -LENGTH - OVER, OVER, BORE_DIA / 2.0), "bore")

    made = [("bearing", body)]
    _inject(comp, made)
    print("built %d bodies in %s" % (len(made), COMPONENT))
    verify(comp)


def verify(comp):
    """Volume against the analytic annulus -- the proof the bore actually cut, the same
    argument scripts/make_bearing_cad.py's own header makes: a solid slug would read
    {solid_slug_mm3:.3f} mm3 instead of {volume_mm3:.3f}.
    """
    bad = _verify_volume(comp, {{"bearing": VOLUME_MM3}}, VOLUME_TOLERANCE)

    body = None
    for b in comp.bRepBodies:
        if b.name == "bearing":
            body = b
    if body is None:
        bad.append("bearing body is missing, so its bore cannot be checked")
    else:
        found = _verify_cyl_faces(body, BORE_DIA / 2.0, axis_is_radial=False)
        print("  %-20s %d bore face(s) at dia %.3f" % ("bearing", len(found), BORE_DIA))
        if len(found) != 1:
            bad.append("bearing has %d bore faces at dia %.3f, wanted 1"
                       % (len(found), BORE_DIA))

    if bad:
        raise ValueError("VERIFY FAILED: " + "; ".join(bad))
    print("  OK")
'''


def main() -> None:
    text = emit()
    print(text)
    if "--write" in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"\n# written to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
