"""Build the two access bulkheads (pass-through plate, nose aft face) as native Fusion
geometry, from design/access_bulkhead.py -- porting scripts/make_access_bulkhead_cad.py
(correction 38) off Onshape.

    python scripts/make_access_bulkhead_cad_fusion.py            # print the script
    python scripts/make_access_bulkhead_cad_fusion.py --write    # and into out/

WHY THIS EXISTS NOW: same reason as scripts/make_seal_cad_fusion.py's own header -- the
hidden 28-body Fusion rebuild that M6 is cutting over from carries `pass_through_plate`
alongside the six parts M1-M5 already migrated, and the migration's answer to "what happens
to the ones nobody ported" is to port them too, not delete them with nothing standing in.

WHAT GETS BUILT, same scope as make_access_bulkhead_cad.py: the pass-through plate (dia
74.8 x 2.4 G-10, 1x dia 8.0 wire bundle feed-through) and the nose aft face (dia 74.8 x 3.2,
1x dia 8.0 connector feed-through).

FRAME -- the MIRROR of make_seal_cad_fusion.py's, not a copy (same reasoning the Onshape
original states): the aft gas seal sits at the module's aft face with its origin on the
disc's aft face, growing forward, into the tube's own modelled span. This plate sits at the
module's FORWARD face (Z 0.000, confirmed off the live Tube body's own bounding box) and
closes the nav bay's aft end, so its origin is on the disc's FORWARD face, growing AFT --
the disc spans Z [0, thickness], inside the tube's own Z [0, 142.92] span, same "the
geometry that gets interference-checked is inside the geometry that exists" reasoning. The
nose aft face is NOT placed -- it closes a cavity (the nose) this project has never
modelled, same reasoning the internal bulkhead is left unplaced in make_seal_cad_fusion.py
-- and is built at its own local origin, Z [0, thickness] at the document's shared root
origin.

VERIFIED against the analytic disc-less-hole volume, same 0.01 mm3 tolerance as the Onshape
original -- "the only proof the hole actually cut rather than landing off the material."
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from design import access_bulkhead as ab
from design.configure import baseline, evaluate
from scripts.fusion_common import FUSION_PRELUDE

OUT = Path(__file__).resolve().parents[1] / "out" / "make_access_bulkhead_cad_fusion_generated.py"

VOLUME_TOLERANCE_MM3 = 0.01

# The module's forward face -- Z 0.000, confirmed off the live Tube body's own bounding box
# (same as the aft face this migration's make_seal_cad_fusion.py measured), not assumed.
MODULE_FORWARD_FACE_MM = 0.0


def _disc_and_holes(r: ab.AccessBulkheadResult):
    b = r.bulkhead
    holes = [(h.name, h.x * 1000.0, h.y * 1000.0, h.diameter * 1000.0)
             for h in ab.hole_layout(r)]
    want = math.pi * b.radius**2 * b.thickness
    for h in ab.hole_layout(r):
        want -= math.pi * (h.diameter / 2.0) ** 2 * b.thickness
    return b.radius * 1000.0, b.thickness * 1000.0, holes, want * 1e9


def emit() -> str:
    ev = evaluate(baseline())
    pt_r, pt_t, pt_holes, pt_want = _disc_and_holes(ab.pass_through_from_evaluation(ev))
    nose_r, nose_t, nose_holes, nose_want = _disc_and_holes(ab.nose_plate_from_evaluation(ev))

    def holes_repr(holes):
        return ", ".join("(%r, %r, %r, %r)" % h for h in holes)

    return f'''"""GENERATED by scripts/make_access_bulkhead_cad_fusion.py -- do not edit this
file. Regenerate rather than patch.

Builds PassThroughPlate (module global frame, forward face at Z
{MODULE_FORWARD_FACE_MM:.4f}) and NoseAftFace (local frame, not placed -- the nose cavity
is not modelled). Idempotent: verifies rather than rebuilds if either component already has
bodies.
"""

{FUSION_PRELUDE}

VOLUME_TOLERANCE_MM3 = {VOLUME_TOLERANCE_MM3!r}
FORWARD_FACE_MM = {MODULE_FORWARD_FACE_MM}

PT_RADIUS_MM = {pt_r!r}
PT_THICKNESS_MM = {pt_t!r}
PT_HOLES = [{holes_repr(pt_holes)}]
PT_WANT_MM3 = {pt_want!r}

NOSE_RADIUS_MM = {nose_r!r}
NOSE_THICKNESS_MM = {nose_t!r}
NOSE_HOLES = [{holes_repr(nose_holes)}]
NOSE_WANT_MM3 = {nose_want!r}

OVER_MM = 1.0


def _build_disc(tbm, cx, cy, z0, z1, radius, holes):
    """A disc from z0 to z1 (mm, z0 < z1) at (cx, cy), each hole its own overshooting cut --
    same "separate cut per hole, overshoot both faces" discipline as the Onshape original."""
    body = _cyl(tbm, cx, cy, z0, z1, radius)
    for (name, hx, hy, hd) in holes:
        tool = _cyl(tbm, cx + hx, cy + hy, z0 - OVER_MM, z1 + OVER_MM, hd / 2.0)
        _cut(tbm, body, tool, name)
    return body


def run(_context: str):
    app = adsk.core.Application.get()
    des = adsk.fusion.Design.cast(app.activeProduct)
    root = des.rootComponent
    tbm = adsk.fusion.TemporaryBRepManager.get()

    # -- Pass-through plate: module global frame, origin on the forward face, growing aft --
    pt_occ, pt_has_bodies = _get_or_create_component(root, "PassThroughPlate")
    if not pt_has_bodies:
        z0 = FORWARD_FACE_MM
        z1 = FORWARD_FACE_MM + PT_THICKNESS_MM
        body = _build_disc(tbm, 0.0, 0.0, z0, z1, PT_RADIUS_MM, PT_HOLES)
        _inject(pt_occ.component, [("pass-through plate", body)])
        print("PassThroughPlate: built, Z %.4f -> %.4f mm" % (z0, z1))
    else:
        print("PassThroughPlate: already has bodies, verifying only")
    bad = _verify_volume(pt_occ.component, {{"pass-through plate": PT_WANT_MM3}}, VOLUME_TOLERANCE_MM3)

    # -- Nose aft face: local frame, NOT placed (no nose cavity modelled) --
    nose_occ, nose_has_bodies = _get_or_create_component(root, "NoseAftFace")
    if not nose_has_bodies:
        body = _build_disc(tbm, 0.0, 0.0, 0.0, NOSE_THICKNESS_MM, NOSE_RADIUS_MM, NOSE_HOLES)
        _inject(nose_occ.component, [("nose aft face", body)])
        print("NoseAftFace: built, local frame Z 0.0000 -> %.4f mm" % NOSE_THICKNESS_MM)
    else:
        print("NoseAftFace: already has bodies, verifying only")
    bad += _verify_volume(nose_occ.component, {{"nose aft face": NOSE_WANT_MM3}},
                          VOLUME_TOLERANCE_MM3)

    if bad:
        raise ValueError("VERIFY FAILED: " + "; ".join(bad))
    print("  OK -- both access bulkheads verified against analytic disc-less-hole volume")
'''


def main() -> None:
    text = emit()
    print(text)
    if "--write" in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"\n# written to {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
